### ISSUE TITLE
ALINA RETEST TeX math not converted when exercises pulled in

### ISSUE THREAD

**Issue by reedstrm** [openstax/webview#1471]
When webview pulls in exercises from exercises.openstax.org, the code to tell mathjax to convert the included TeX math is not firing correctly. See: http://cnx.org/contents/bDIuMp-w@1.1:XwiMLb76@2/Synthesis-of-Biological-Macrom#fs-id1425951 

![d0347078-a26e-11e6-83aa-c944de55029b](https://cloud.githubusercontent.com/assets/253212/20008993/b8b11fb2-a270-11e6-8b2f-d0c39249cd6c.png)

**Comment by openstaxalina** [comment]
aHA!  Is this still an issue?  Appears to be, at least in some cases...see: https://trello.com/c/reT0cIeF/222-investigate-latex-issue
