### ISSUE TITLE
use yarn instead of npm install to have precise versions

### ISSUE THREAD

**Issue by philschatz** [openstax/webview#1547]
This is a recurring problem: "It builds fine for me, what packages did you build with?"

Yarn makes sure we all use the same versions of packages. It's similar to a `Gemfile.lock` in ruby land

/cc @reedstrm because of the frustration this causes.

**Comment by reedstrm** [comment]
I thought bower (and bower.json) was supposed to handle that? Or is there an issue where that only controls direct dependencies, those may drag in other things in a less constrained way?

**Comment by RoyEJohnson** [comment]
A comparison: https://www.slant.co/versus/5094/17851/~bower_vs_yarn

**Comment by openstaxalina** [comment]
@philschatz is this still an issue?

**Comment by philschatz** [comment]
This may no longer be an issue since we use tarballs to deploy the code but I think it's still good practice to explicitly update our package dependencies so please leave it open 😄

**Comment by m1yag1** [comment]
npm output when installing dependencies has a warning that bower is deprecated.

```
npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
```
