### ISSUE TITLE
use absolute paths in nginx.development.conf

### ISSUE THREAD

**Issue by philschatz** [openstax/webview#1554]
Newer versions of nginx require an absolute path.

We would need to add a new task to grunt that:

1. takes a template file and fills in the absolute path (and port?) and saves it as `nginx.development.conf`
2. runs `grunt nginx:start`

It would probably be run by running `npm start`

**Comment by reedstrm** [comment]
Perhaps do it as part of grunt dist, then provide both compiled and dev on diff ports

**Comment by reedstrm** [comment]
The absolute path thing is truly annoying - it even applies to the argument to the `-c` option, so I have to call it as `nginx -c "$PWD"/nginx.development.ini`

**Comment by openstaxalina** [comment]
@philschatz is this still an issue?

**Comment by philschatz** [comment]
Yes, unfortunately
