### ISSUE TITLE
Implement mathml reading w/ explorer.js

### ISSUE THREAD

**Issue by reedstrm** [openstax/webview#1585]
Currently Vox (and other screen readers) skip the math
The explorer.js plugin as used here:
https://github.com/openstax/tutor-js/pull/1902/files
enables good reading.

**Comment by openstaxalina** [comment]
See also: https://trello.com/c/hKibrkht/173-a11y-enable-assistivemml-so-mathml-is-read-by-screenreaders-1

...seems like AssistiveMML is an alternative.  
Whoever works on the AssistiveMML card may want to look at explorer.js as well/instead.
