### ISSUE TITLE
Too many different links, to the same page in a book, is sent to Google Analytics

### ISSUE THREAD

**Issue by tomekstach** [openstax/webview#1601]
Google Analytics should receive only canonical links - now, GA receives all versions of link to the single page in the book.

The problem is with too early sending requests to the GA. `canonicalizePath` in the *src/scripts/modules/media/body/body.coffee* do a replace previous URL with the canonical path in the end of everything - because earlier it doesn't know that `canonicalPath` is not in `currentRoute`.

**The main question is:** how to send requests to the GA after the real canonization of the path? Or maybe will be better to send requests to GA in the end of everything? If yes, how to do that?

**Comment by tomekstach** [comment]
https://github.com/tomekstach/webview/commit/aa663f6067894056f498fd85da224ce00070fbde

I've did only two changes:

1. I added request to the `trackAnalytics` in the end of `canonicalizePath` in the *src/scripts/modules/media/body/body.coffee*
2. I removed `@listenTo(@model, 'change:googleAnalytics', @trackAnalytics)` from the *src/scripts/modules/media/media.coffee*

And it works: request to the GA is sent after the replace URL to the canonical path, but I removed `listenTo` part and it doesn't work properly.

I want to move a part of code, which makes changes in the Google Analytics, to the end of process and then restore 'listenTo' part - but I am not sure how to do this.

**Comment by tomekstach** [comment]
@philschatz Wojtek has sent me a two more links:

- [documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications)
- [pageVisibilityTracker](https://github.com/krisu7/autotrack/blob/master/docs/plugins/page-visibility-tracker.md)

**Comment by philschatz** [comment]
Oh nice! Both options (using the [autotrack](https://github.com/googleanalytics/autotrack) project and the `urlChangeTracker`) seem promising. I can try creating a Pull Request (or 2) so folks can evaluate and try it out.

**Comment by philschatz** [comment]
Ah, I misunderstood. I think that the `urlChangeTracker` plugin in `autotrack` will still send multiple pageview events since the URL changes multiple times. 

Also, it seems like there is no easy way to add/remove tracking codes when the content changes. Currently, we explicitly call the `pageView` event for all the tracking codes for a piece of content. With `autotrack` it seems like we would need to remember which tracking codes are registered with `ga()` and make sure to de-register them right before `autotrack` sends an event to Google Analytics.

Does that sound right?

I am continuing to look at this double-sending problem (& the commit you mentioned)

**Comment by tomekstach** [comment]
Yes, you are right - but in the documentation I've found part [Customizing what is considered a URL change](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/url-change-tracker.md#customizing-what-is-considered-a-url-change). Maybe this is a right solution for the problem with redirects (customizing when the request should be send to GA).

You are right about add/remove tracking codes - it might be hard to do this in a right way. But they have solutions for many different problems - maybe also they have something for that. I will try to find something for this :)

**Comment by kerwinso** [comment]
Still finding this while testing on staging after #1630 was merged. The following 3 URLs were tested simultaneously:
- https://staging.cnx.org/contents/65bd3065-1509-46ca-8890-2619bb6e6b24@5
- https://staging.cnx.org/contents/Zb0wZRUJ
- https://staging.cnx.org/contents/Zb0wZRUJ@5

They are being reported to GA as 3 separate URLs:

![image](https://user-images.githubusercontent.com/11298165/40810467-79e5a086-64f3-11e8-819e-28f32beaa9ed.png)
