### ISSUE TITLE
setup cache-control and versioned filenames for minified JS

### ISSUE THREAD

**Issue by reedstrm** [openstax/webview#1618]
Currently, webview has a one-hour caching lifetime for the 2 (soon to be 3) primary files that the browser needs to render the site: scripts/main.js, scripts/settings.js. and locale/[your-locale-here]/dictionary.ftl There is _no_ cache-control set for index.html, which hard codes the path to scripts/require.js, which is also currently not cache-controlled.

This will continue to work for deployments, as long as any changes we make to backend/frontend communications are carefully written to be both forward and backward compatible. If we _do_ need a coordinated release in the future, we'll have a 1 hour window when the site may break.

While I'm a fan of always writing forward and backward compatible changes (to the point where I advocate releasing any backend changes _first_ if at all possible), we should consider adding "cache-busting" settings to make our minified JS files have unique per-release filenames, and set an appropriately short cache-control based lifetime on index.html, and whatever magic is needed for require.js

**Comment by kerwinso** [comment]
Ross asking @philschatz for input

**Comment by openstaxalina** [comment]
@reedstrm , is this related to https://trello.com/c/jPHr1INO/37-files-do-not-have-a-cache-control-header-so-browsers-will-cache-them?
