### ISSUE TITLE
<newline> changes related to Different font color in list of authors

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#1666]
![font_colour](https://user-images.githubusercontent.com/40228854/41859346-4b7b5166-789c-11e8-9fd3-d80bc54f3a3f.JPG)
Link to the issue: https://devb.cnx.org/contents/GFy_h8cu@10.120:fVAf83sY@13/Preface

**Comment by helenemccarron** [comment]
This looks like a CNXML -> HTML transforms issue. 

The CNXML looks like this:
```
<para>Julie  Adams, Aurora University <newline/>

Summer Allen, Brown University <newline/>

James  Bader, Case Western Reserve University<newline/> 
.
.
.
</para>
```
is being converted into 
```
<p>Yael Avissar (Cell Biology), Rhode Island College <div data-type="newline"><br/></div>

Jung Choi (Genetics), Georgia Institute of Technology <div data-type="newline"><br/></div>

.
.
.
</p>
```

This seems to be working in both the PDF and in the complete baked HTML but on webview, the `p` tag is closed right before the first div. @philschatz I am not sure where we should start looking to solve this issue?

**Comment by PiotrKozlowski** [comment]
@helenemccarron I think that I can't help you with it at this stage.

**Comment by openstaxalina** [comment]
I suggest that we move this to a future milestone; the valid XHTML work is not within scope for a two-week release.  The existing display is acceptable for a MVP.

**Comment by openstaxalina** [comment]
@helenemccarron and I agree this is out of scope.  Removing from the Assignable Webview milestones.

**Comment by PiotrKozlowski** [comment]
This should be fixed after merging and applying https://github.com/Connexions/rhaptos.cnxmlutils/pull/170

**Comment by helenemccarron** [comment]
`<p><span data-type='newline'></p>`
