### ISSUE TITLE
Develop a flowchart for logical content paths

### ISSUE THREAD

**Issue by brittweinstein** [openstax/webview#1751]
## Description

As a developer, I'd like a flowchart indicated the logical paths content takes to end up in baked states (e.g. success, failed, fallback, etc.), so that I can reference our baking logic at a glance rather than code diving.

@brittweinstein commented on [Thu Jul 26 2018](https://github.com/Connexions/content-managers/issues/177)

## Acceptance Criteria

- Provides a visual flowchart focusing on the end states content can be in. The flow paths should indicate how content gets to the end state.
- Narrative explanation of the flow organized by end state.

**Comment by pumazi** [comment]
I've updated this with a story for the description and accept criteria.

**Comment by openstaxalina** [comment]
@kerwinso do you have a diagram like this?  Alan thought you may have a draft of something like this.

**Comment by kerwinso** [comment]
@openstaxalina No I don't

**Comment by brittweinstein** [comment]
@kevinburleigh75 do you have something like this?
