### ISSUE TITLE
Padding Adjustments to Assessments in Econ 2e Appendix

### ISSUE THREAD

**Issue by openstaxalina** [openstax/webview#1914]
webview on the left; PDF on the right
![econ2eappendixquestions](https://user-images.githubusercontent.com/7863733/45118265-aa0dd000-b11d-11e8-9b68-b01b988d4815.png)

Link to content on staging:  https://staging.cnx.org/contents/vEmOH-_p@5.1:pAeLAwQZ@7/A-The-Use-of-Mathematics-in-Principles-of-Economics#CNX_Econ_A01_021

I am not sure whether this impacts all baked books.

We can defer this if needed.

**Comment by PiotrKozlowski** [comment]
We can change padding of this elements but this will apply to all paragraphs inside `[data-type="exercise"] .os-problem-container` so it can cause additional reggresion testing.

**Comment by openstaxalina** [comment]
Thanks @PiotrKozlowski - I'm moving this to the Books Backlog for a possible future release.

**Comment by Adrianltd** [comment]
@openstaxalina the fix referenced above will impact all `os-problem-container` paragraphs within exercises in appendices in all baked books. Is this solution acceptable?

**Comment by PiotrKozlowski** [comment]
@Adrianltd Maybe something like this:
```
[data-type="problem"] .os-problem-container p:first-child {
    margin-top: 0 !important;
}
```

**Comment by brittweinstein** [comment]
Decision: Leave the left padding as is.

**Comment by MartaSztuka** [comment]
Padding is even now, is this acceptable?
![Screenshot from 2019-05-21 17-38-36](https://user-images.githubusercontent.com/47241114/58152890-ff6b1c80-7c6d-11e9-94db-a5ea601e9b47.png)

**Comment by MartaSztuka** [comment]
It seems fix worked and paddings have slightly different height, but it would be better to make it more distinctive, as in pdf. I would suggest making double leading between question and following exercise.
![Screenshot from 2019-05-22 09-54-15](https://user-images.githubusercontent.com/47241114/58157008-ba4be800-7c77-11e9-8900-fd3bd1731748.png)

**Comment by MartaSztuka** [comment]
Leading looks good now. Tested on katalyst01.
https://katalyst01.cnx.org/contents/vEmOH-_p@7.1:pAeLAwQZ@10/A-The-Use-of-Mathematics-in-Principles-of-Economics
![Screenshot from 2019-05-22 11-04-33](https://user-images.githubusercontent.com/47241114/58161901-6e9e3c00-7c81-11e9-817b-7c45945715cc.png)
