### ISSUE TITLE
WAITING - retest on staging after March 18 deploy: Small distance between objects

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2060]
On katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.15:vFlmuf2H@12/5-6-Graphing-Systems-of-Linear-Inequalities) between mathematical object and `<p>` there is too small distance:

![distance](https://user-images.githubusercontent.com/40228854/48486052-b2b80c00-e81a-11e8-865c-62042f998572.JPG)

**Comment by PiotrKozlowski** [comment]
It may be realted to #1666 
Waiting for response in #2071

**Comment by theresamasciale** [comment]
After regression testing, space between math object and para text still remains the same.

![screen shot 2019-02-05 at 8 59 30 am](https://user-images.githubusercontent.com/47189012/52281802-78936d80-2924-11e9-9d3b-df494b3d24f9.png)

**Comment by openstaxalina** [comment]
This should be retested on staging.cnx.org on Monday.  @omehes would you be able to test this on staging after the deploy on Monday?  Britt is going to follow up with you in scrum.

**Comment by omehes** [comment]
@alina I verified this on qa.cnx.org. Looks good. I will check it again on staging on Monday.

**Comment by omehes** [comment]
@openstaxalina 
Reverified on staging.cnx.org
Rebaked the book but it is still the same, no fix visible.

**Comment by openstaxalina** [comment]
@omehes my apologies -- it looks like this didn't make it into our code freeze for 3/12 production deployment.  This should be on staging the week of March 18.

**Comment by omehes** [comment]
@openstaxalina OK. I will test it after March 18th.

**Comment by brittweinstein** [comment]
@omehes this should be ready for retesting

**Comment by omehes** [comment]
verified on staging
fixed

{"date": "2019-03-19 14:59:06 CDT",
 "webview": "6402e50a45792a3ce1cc8479eddc9e70f8685e39 (v0.48.0)",
 "cnx-archive": "4.11.0",
 "cnx-publishing": "0.16.2",
 "oer.exports": "crusty.cronut v0.73.0",
 "press": "8.0.2",
 "cnx-deploy": "v2.38.4-4-g0d6ae71"
}


![smallSP](https://user-images.githubusercontent.com/44207656/54643582-4a499780-4a65-11e9-8bae-a78a8142e011.png)
