### ISSUE TITLE
Tokens and block equations

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2069]
On katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.15:tegV4wXG@5/4-5-Use-the-Slope-Intercept-Form-of-an-Equation-of-a-Line) block equations should be displayed next to the tokens.

![tokens](https://user-images.githubusercontent.com/40228854/48618906-03567300-e99b-11e8-8897-c1e300ad3a3a.JPG)

**Comment by PiotrKozlowski** [comment]
Issues:
- those lists are hardcoded
`<p id="fs-id1169751869658"><span class="token">ⓐ</span></p>`
- between `token` and `equation` there is `newline` #1666 which is breaking html so math is outside paragraph

After merging #1666 math will be again inside paragraph, however it will not be next to the tokens. To make this happens this list has to be created as normal list with proper attributes.

cc @openstaxalina

**Comment by wilkus27** [comment]
I have already created issue about the first problem: https://github.com/Connexions/webview/issues/2071. @openstaxalina @lwtchu In this case, should this issue have higher priority?

**Comment by PiotrKozlowski** [comment]
If you can confirm that both of lists from #2071 are created in the same way in the content then it will be related to #1666

**Comment by PiotrKozlowski** [comment]
I still believe this is related to #1666, because math is outside paragraph - newlines are breaking paragraphs.

**Comment by theresamasciale** [comment]
After regression testing, block equations are still beneath their tokens, but they're now closer. See screenshot. 
![screen shot 2019-02-05 at 8 54 35 am](https://user-images.githubusercontent.com/47189012/52281561-fe62e900-2923-11e9-83a3-43728eabcd28.png)

**Comment by lwtchu** [comment]
Not an issue. Closed
