### ISSUE TITLE
Change in account info in legacy should update in webview too 

### ISSUE THREAD

**Issue by omehes** [openstax/webview#2081]
Steps:
1. log in to legacy
2. change First name (also in Full Name) of somebody who has published content (book)
3. save and log out
4. log back in to legacy
Expected: the change to the name should still be there
Actual: the change to the first name is still there (correct) 
5. check webview (staging.cnx.org) for one of the collections published by that user
Expected: the change in name should be reflected under author's name
Actual: the name is not changed in webview and it still shows the old name

Test case: https://openstax.testrail.com/index.php?/tests/view/352081&group_by=cases:section_id&group_order=asc&group_id=8033

**Comment by openstaxalina** [comment]
Related/original issue that I am going to close: https://github.com/Connexions/webview/issues/1990

**Comment by omehes** [comment]
I tested this on the latest deployed cnx on staging and:
- if I change First name and also Full Name in legacy of somebody who has published content (book) and I save the changes and log out and Publish the book, afterwards I see the changed name in webview too. If I don't (re)publish the book, name will not be changed in webview.

Discussed this with the team at standup.

staging.cnx.org versions:
{"date": "2018-11-30 13:34:04 CST",
 "webview": "969e07959a31572cdb61fec6f4573b5644d55637 (v0.42.0)",
 "cnx-archive": "4.6.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "worried.werewolf v0.67.0",
 "press": "7.0.1",
 "cnx-deploy": "v2.32.1"
}

**Comment by openstaxalina** [comment]
The underlying issue is that books are showing with "OpenStax College" as the author on cnx.org, although content managers adjusted the name on the Account "OpenStaxCollege" (in Legacy) to be "OpenStax".   Ross is going to manually fix the database for now, to relieve the time pressure and allow us to fix this bug properly once it can be reproduced.

**Comment by brittweinstein** [comment]
@Bkblodget do we want to push this to Q2?

**Comment by Bkblodget** [comment]
related to https://app.zenhub.com/workspaces/cnx-team-5af1f4cc12da5e6d74331b60/issues/openstax/cnx/250
