### ISSUE TITLE
User message should display on advanced search if no criteria is entered

### ISSUE THREAD

**Issue by edwoodward** [openstax/webview#2086]
When a user clicks the Search button on the Advanced Search page, the page blinks, but the user does not know why. We should inform the user with a message on the page that criteria is required for a search. The Message could be...

> Please enter search criteria

Some old code that might help show how to implement this

[Donate Form HTML](https://github.com/Connexions/webview/blob/537f5f2204c2f254bd4bd01d7c1f995459a5a638/src/scripts/pages/donate/form/form-template.html)
[Donate Form Coffeescript](https://github.com/Connexions/webview/blob/537f5f2204c2f254bd4bd01d7c1f995459a5a638/src/scripts/pages/donate/form/form.coffee)
[ValidationHelper](https://github.com/Connexions/webview/blob/1a986e03fd1c66d2337792a98aed0683e37fd68b/src/scripts/helpers/validation.coffee)

**Comment by brittany-johnson** [comment]
<img width="1036" alt="screen shot 2018-12-04 at 11 55 37 am" src="https://user-images.githubusercontent.com/24909007/49462593-10a59700-f7bc-11e8-8076-c6ffa604c698.png">
@openstaxalina This is the message that will display when a user tries to submit this form without entering any search criteria

**Comment by openstaxalina** [comment]
@brittany-johnson this looks great!  I can't remember; are we asking @Stackblocks to test these?  I am going to assign to him and wait to be told if I am wrong :-P

**Comment by Stackblocks** [comment]
@brittany-johnson What's the status on this?

**Comment by openstaxalina** [comment]
This is ready for testing when @Stackblocks is back.

**Comment by omehes** [comment]
@brittweinstein @Stackblocks Please note that while exploratory testing search, I saw the following:
- in Advanced search click the Submit button without entering anything in the fields
screen jumps and flashes but no warning message appears
- click Submit button again
A message in pink rectangle appears: "Please enter search criteria." It only appears after second click on the Submit button.

**Comment by openstaxalina** [comment]
Thanks, Otto!  @brittany-johnson would you be able to take a look at the behavior Otto described above?

**Comment by Stackblocks** [comment]
QED 

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4dccb8f6-f191-4de4-b42b-2944ba420ebe)
