### ISSUE TITLE
Message should display if only Sort By criteria is selected on Advanced Search

### ISSUE THREAD

**Issue by edwoodward** [openstax/webview#2091]
To recreate the issue

1. Go to https://cnx.org/search
2. Select another option in the Sort By dropdown
3. Click Submit button
4. User gets an empty search result

We should display a message to select or enter criteria if only Sort By has been modified.

**Comment by openstaxalina** [comment]
Currently the message is: `No results found. Please try expanding your search.`

The message should be: `Please enter search criteria.`

**Comment by openstaxalina** [comment]
@brittany-johnson this is ready (I think -- let me know if you need more info).  This can slide to the next release if needed.

**Comment by brittany-johnson** [comment]
@Stackblocks Fixed with https://github.com/openstax/webview/issues/2086

**Comment by Stackblocks** [comment]
QED 

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/178766cc-1044-46e0-93d4-c90aa1ab44fd)
