### ISSUE TITLE
PhET simulation embedded tiny

### ISSUE THREAD

**Issue by oscryan** [openstax/webview#2099]
https://cnx.org/contents/Ax2o07Ul@14.4:fsw4uvhV@10/30-2-Discovery-of-the-Parts-of-the-Atom-Electrons-and-Nuclei

The markup includes size specifications (width=“660” height=“371.4") which show right in the editor but are not being carried out in webview.

**Comment by openstaxalina** [comment]
@brittany-johnson is this something you'd be interested/willing to take a look at, maybe sometime next week after code freeze? 
cc @helenemccarron 
cc @Bkblodget

**Comment by Bkblodget** [comment]
@openstaxalina - @edwoodward  believes this problem may originate with a sizing parameter within the `<note>` tag that ignores or suppresses the sizing specifications given within the `<iframe>` tag.

**Comment by brittweinstein** [comment]
Books team discussed this in scrum and there is only an <iframe> width specification in content. Can you please specify where any other width parameters are seen?

**Comment by Bkblodget** [comment]
@edwoodward could you provide where the books team can find the <note> sizing specifications you mentioned to me?

**Comment by openstaxalina** [comment]
https://github.com/openstax/webview/issues/2121 may be related

**Comment by omehes** [comment]
verified. fixed

{"date": "2019-02-04 09:55:02 CST",
 "webview": "9e7f3093433af0351140f86624fd5356a1278f53 (v0.45.0)",
 "cnx-archive": "4.8.0",
 "cnx-publishing": "0.15.0",
 "oer.exports": "astonishing.applepie v0.71.0",
 "press": "8.0.2",
 "cnx-deploy": "v2.36.0"
