### ISSUE TITLE
Not Converted Yet error

### ISSUE THREAD

**Issue by omehes** [openstax/webview#2100]
Go to page: https://staging.cnx.org/contents/CzMnNGya@2/Electric-Circuits-Resistance

There will be markers for error in the CNXML to HTML transform. 
In this case, why is `para` an error since we have paragraphs everywhere in all the content. 

Discussed with @reedstrm  

![phy-not.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/24ecc14c-c6ec-4325-891c-911d5a44c242)

**Comment by openstaxalina** [comment]
@reedstrm will look into this alongside @brittany-johnson and @helenemccarron.

**Comment by Bkblodget** [comment]
Another instance of this happens in https://katalyst01.cnx.org/contents/W8wOWXNF@18.8:tiLfHQfp@5/9-4-Divided-Government-and-Partisan-Polarization - from #2124.

A temporary fix for one instance of this in American Government was implemented with https://github.com/Connexions/rhaptos.cnxmlutils/pull/166

**Comment by reedstrm** [comment]
I've created a test collection on staging that contains all 222 instances of `NOT CONVERTED YET`
https://staging.cnx.org/contents/6K-deGrs@2.1

**Comment by brittweinstein** [comment]
Related issue in Principles of Management: https://app.zenhub.com/workspaces/cnx-team-5af1f4cc12da5e6d74331b60/issues/openstax/cnx-recipes/806

**Comment by Bkblodget** [comment]
A workaround fix was implemented for this via content. This bug is to be reevaluated once other transform/validating XHTML work is completed to see if it is still a problem.

**Comment by brittweinstein** [comment]
I am closing as this is a longterm known issue. We can come back to this in the archives if needed.
