### ISSUE TITLE
Missing exercises

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2108]
On katalyst01 in three chapters (Chapter 5, 11 and 13) there are missing exercises.

**Chapter 5** https://katalyst01.cnx.org/contents/Sr8Ev5Og@9.20:czXGAjFU@9.20/Review-Questions

![ch_5](https://user-images.githubusercontent.com/40228854/49526682-a28ecc00-f8b0-11e8-901f-261ef6218910.JPG)

PDF:

![ch_5_pdf](https://user-images.githubusercontent.com/40228854/49526696-a9b5da00-f8b0-11e8-8737-4f6ee8ea4ade.JPG)

**Chapter 11** https://katalyst01.cnx.org/contents/Sr8Ev5Og@9.20:gYBbkueN@9.20/Review-Questions

![ch_11](https://user-images.githubusercontent.com/40228854/49526754-cb16c600-f8b0-11e8-8b63-8a38378e459f.JPG)

PDF:

![ch_11_pdf](https://user-images.githubusercontent.com/40228854/49526766-d2d66a80-f8b0-11e8-8667-3c14f6dd3474.JPG)

**Chapter 13** https://katalyst01.cnx.org/contents/Sr8Ev5Og@9.20:U91uCrgo@9.20/Review-Questions

![ch_13](https://user-images.githubusercontent.com/40228854/49526824-f0a3cf80-f8b0-11e8-917d-ed7e5dceaac4.JPG)

PDF:

![ch_13_pdf](https://user-images.githubusercontent.com/40228854/49526852-fbf6fb00-f8b0-11e8-962d-911df12e3085.JPG)

**Comment by openstaxalina** [comment]
I am guessing that although @marcjeannott put these exercises back into the content, but perhaps one or two modules didn't make it in the migration to katalyst01.  @marcjeannott if you could verify that these assessments are there on production, we can close this issue.

**Comment by marcjeannott** [comment]
Verified on production
