### ISSUE TITLE
Transforms process failed on University Physics Volume 1, 2 and 3 books (all baked books)

### ISSUE THREAD

**Issue by omehes** [openstax/webview#2112]
As part of the transforms testing, PR #170 https://github.com/Connexions/rhaptos.cnxmlutils/pull/170

When inspecting University Physics Volume 1, 2 and 3, I still find  `<div data-type=“newLine”>` but no `<span...`

Note, these books are all baked.

Steps are in: 
https://docs.google.com/document/d/1LUp8rt1ujaj6l79012-j_d0DC90GT7Rf18pJsk2W5tg

**Comment by omehes** [comment]
@philschatz Sorry. Forgot to add it: https://qa.cnx.org/contents/1Q9uMg_a@10.12:Gofkr9Oy@15/Preface
All 3 books of University Physics Volume 1, 2 and 3 have the same issue (they are all baked).

**Comment by brittweinstein** [comment]
@philschatz should we move this over for @omehes to test since that's where the attached PR is?

**Comment by philschatz** [comment]
Sure but what's the reason for moving the issue? Won't we lose all the discussion history?

**Comment by brittweinstein** [comment]
@philschatz this is just changing pipeline so otto can test, not closing the issue.

**Comment by omehes** [comment]
verified on qa.cnx.org on Uni Phys vol1 and 2
fixed

**Comment by omehes** [comment]
verified on all Univ Phys books 1,2,3
Preface
and more chapters in each volume
staging.cnx.org
FIXED

{"date": "2019-03-04 14:30:54 CST",
 "webview": "6fea2e99064f4522c968ac6b4ada6203d9eb9e5d (v0.47.0)",
 "cnx-archive": "4.11.0",
 "cnx-publishing": "0.15.1",
 "oer.exports": "crusty.cronut v0.73.0",
 "press": "8.0.2",
 "cnx-deploy": "v2.38.2"
}
