### ISSUE TITLE
NEWLINE TESTING: <div> to <span> newline transform change causes list to be on a single line

### ISSUE THREAD

**Issue by edwoodward** [openstax/webview#2127]
Production URL - https://cnx.org/contents/vEmOH-_p@6.8:2bGSjz1y@7/17-2-How-Households-Supply-Financial-Capital

On production,  the list looks as expected, but with excess space.
![screenshot from 2018-12-11 12-56-16](https://user-images.githubusercontent.com/1394695/49823177-ad2fe200-fd44-11e8-98de-034da9fe8f18.png)

HTML on production
![screenshot from 2018-12-11 12-58-53](https://user-images.githubusercontent.com/1394695/49823257-de101700-fd44-11e8-8902-13ff9fde2699.png)

Staging URL - https://staging.cnx.org/contents/vEmOH-_p@7.1:2bGSjz1y@7/17-2-How-Households-Supply-Financial-Capital

On staging. the list is being displayed as one line
![screenshot from 2018-12-11 13-03-03](https://user-images.githubusercontent.com/1394695/49823432-4c54d980-fd45-11e8-97df-d5ba8937bd49.png)

HTML on staging
![screenshot from 2018-12-11 13-04-01](https://user-images.githubusercontent.com/1394695/49823453-58409b80-fd45-11e8-9faf-78df15297216.png)

**Comment by openstaxalina** [comment]
This is occurring because the stepwise lists have a flex element enabled.  When we disable the flex element, the list displays properly.  @PiotrKozlowski could you create a PR that disables the flex element on stepwise lists?  However, we still need to handle stepwise lists appropriately in Chemistry and DevMath.  Is there a solution that accommodates both displays?
cc @helenemccarron

**Comment by PiotrKozlowski** [comment]
Display flex will work only after recipie change will be applied to all books with stepwise class.

For now I've just deleted all styling for `.stepwise` so it will behave as a normal list.

The easiest solution to make it work on all books and do not break others will be to change `stepwise` class to `os-stepwise` wile baking and style only the second one.

**Comment by wilkus27** [comment]
Verified on katalyst01 (https://katalyst01.cnx.org/contents/vEmOH-_p@6.4:2bGSjz1y@7/17-2-How-Households-Supply-Financial-Capital)

![lists](https://user-images.githubusercontent.com/40228854/50637285-a702df00-0f59-11e9-8723-027bcbce3f9c.JPG)

**Comment by brittweinstein** [comment]
@omehes Can we close this as well?

**Comment by omehes** [comment]
@brittweinstein I verified on latest build on staging. It looks worse now, numbering disappeared and items are in one line. See attached screen shot.

![spacing1.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/6bb9f4a8-fad0-428f-99bb-ffb2d07e134c)

"date": "2019-01-10 11:27:24 CST",
 "webview": "9afc493b8f9c2fee608555a680fccda15d57d569 (v0.43.0)",
 "cnx-archive": "4.7.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "xiao.xiao v0.68.0",
 "press": "7.0.1",
 "cnx-deploy": "v2.33.5"

**Comment by brittweinstein** [comment]
@omehes is there anything new on this? Perhaps it does need to be rebaked?

**Comment by omehes** [comment]
@brittweinstein @Bkblodget No news on this. I was asking the same, whether it needs rebaking to see if it works.

**Comment by PiotrKozlowski** [comment]
@omehes @brittweinstein @Bkblodget It should look like in screenshot from @wilkus27 
So it needs to be deployed from master and book should be rebaked.

**Comment by omehes** [comment]
I reverified this on latest deployed staging on Chrome and FF. Looks nice with single spacing. Fixed

{"date": "2019-01-11 15:20:09 CST",
 "webview": "65e33ad4775417bd5dfcb698d5cab69f1d594466 (v0.44.0)",
 "cnx-archive": "4.8.0",
 "cnx-publishing": "0.15.0",
 "oer.exports": "ymmy.yeti v0.69.0",
 "press": "8.0.1",
 "cnx-deploy": "v2.34.1"
}
