### ISSUE TITLE
NEWLINE TESTING: some <div... is not transformed to <span... in Polish book

### ISSUE THREAD

**Issue by omehes** [openstax/webview#2131]
In Polish book "Fizyka dla szkół wyższych. Tom 1" and some sections (baked):
https://staging.cnx.org/contents/TqqPA4io@1.107:jsLPl4e-@1.107/Rozwi%C4%85zania-zada%C5%84

some <div elements are not transformed to <span... See the attached screenshot. This applies to more modules which have <div elements instead of <span...

also:
https://staging.cnx.org/contents/TqqPA4io@1.107:USnRLiXz@4/E-Wzory-matematyczne
and
sections: 2.3, 3.6, 7.1, C, E, Podsumowanie rozdziału (7. and 9.)

**Comment by openstaxalina** [comment]
only one instance of newline in 2.3, and it's a div:
<img width="1440" alt="screen shot 2018-12-11 at 3 20 22 pm" src="https://user-images.githubusercontent.com/7863733/49831009-68ae4180-fd58-11e8-93b7-7b43aafb9cca.png">

**Comment by openstaxalina** [comment]
11 instances of newline in 3.6; some are math and the rest are divs: 
https://staging.cnx.org/contents/TqqPA4io@1.107:rdURYw3u@4/3-6-Wyznaczanie-r%C3%B3wna%C5%84-ruchu-metod%C4%85-ca%C5%82kowania

**Comment by philschatz** [comment]
@openstaxalina Not all newlines were being converted to a span. The one in the screenshot is in a list. I created a new Pull Request but I am not sure who should review: https://github.com/Connexions/rhaptos.cnxmlutils/pull/174

**Comment by brittweinstein** [comment]
@Adrianltd would you mind reviewing this PR? When it has been reviewed, please assign to @omehes for qa testing.

**Comment by Adrianltd** [comment]
I've assigned @omehes to that PR mentioned before.

**Comment by brittweinstein** [comment]
@Adrianltd are we ready to close this?

**Comment by Adrianltd** [comment]
@brittweinstein https://github.com/openstax/rhaptos.cnxmlutils/pull/174 is not merged yet, so I don't think so. It still needs review of 3 devs. And after that @omehes should test the fix.

**Comment by omehes** [comment]
Notes from @reedstrm : 
I have verified that _only_ Polish books are impacted by the problem, BTW. Here's the 27 impacted modules (based on `//x:div[contains(@data-type, "newline")]` ):
                             name                              | moduleid 
---------------------------------------------------------------+----------
 Potencjał elektryczny i różnica potencjałów                   | m67174
 Najważniejsze stałe fizyczne                                  | m65853
 Siła magnetyczna działająca na przewodnik z prądem            | m67203
 Pole magnetyczne cienkiego, prostoliniowego przewodu z prądem | m67209
 Powierzchnie ekwipotencjalne i przewodniki                    | m67177
 Zastosowanie elektrostatyki                                   | m67178
 Działania na wektorach                                        | m65744
 Mechanizmy przekazywania ciepła                               | m67146
 Widma atomowe i promieniowanie rentgenowskie                  | m68256
 Wzory matematyczne                                            | m65855
 Rozkład prędkości cząsteczek gazu doskonałego                 | m67150
 Prawo Coulomba                                                | m67162
 Dipole elektryczne                                            | m67166
 Zastosowania sił i pól magnetycznych                          | m67206
 Reguła Lenza                                                  | m67217
 Proces adiabatyczny gazu doskonałego                          | m67242
 Obliczanie potencjału elektrycznego                           | m67175
 Wypadkowa sił i moment sił działających na pętlę z prądem     | m67204
 Związek między wielkościami w ruchach obrotowym i postępowym  | m65793
 Zderzenia w wielu wymiarach                                   | m65787
 Wyznaczanie równań ruchu metodą całkowania                    | m65753
 Ruch po okręgu                                                | m63775
 Prawa Kirchhoffa                                              | m67195
 Pola magnetyczne i ich linie                                  | m67201
 Mikroskopowy model dielektryka                                | m67184
 Entropia w skali mikroskopowej                                | m67158
 Wyznaczanie natężenia pola elektrycznego rozkładu ładunków    | m67164
(27 rows)

**Comment by openstaxalina** [comment]
@PatBoj rebaked the Polish books on staging today, and he is not seeing this fixed.  @brittweinstein to follow up with Ross & Otto at scrum.

@helenemccarron recommends using katalyst01 as a testing server.

**Comment by openstaxalina** [comment]
We can also use qa.cnx.org as a testing server; University Physics volume 1 is on that server.

**Comment by omehes** [comment]
Verified on qa, katalyst01 and staging.
After rebaking 'Fizyka dla szkół wyższych. Tom 1' the fix is visible on qa.cnx.org BUT NOT on staging or kat01.

Note, that qa has only Tom 1 book.

Discussed at standup - the fix will be in the next release not the current one.

@PiotrKozlowski

**Comment by brittweinstein** [comment]
@omehes could you verify this on staging?

**Comment by brittweinstein** [comment]
Assigning to @pumazi for tagging upon release

**Comment by omehes** [comment]
@brittweinstein 
Verified Tom 1 book on qa.cnx.org. All sections verified have <span...newline>. Didn't come across any <div. Seems to be fixed. Will reverify on staging.cnx.org on/after Monday.

**Comment by omehes** [comment]
Verifying these cases after rebaking polish books: 
staging.cnx.org

Potencjał elektryczny i różnica potencjałów                   | m67174 - Tom2, 7.2 - 
 Najważniejsze stałe fizyczne                                  | m65853 - Tom1, Tom2, Tom3, C - 
 Siła magnetyczna działająca na przewodnik z prądem            | m67203 - Tom2, 11.4 - None
 Pole magnetyczne cienkiego, prostoliniowego przewodu z prądem | m67209 - Tom2, 12.2 - None
 Powierzchnie ekwipotencjalne i przewodniki                    | m67177 - Tom2, 7.5 - None
 Zastosowanie elektrostatyki                                   | m67178 - Tom2, 7.6 - None
 Działania na wektorach                                        | m65744 - Tom1, 2.3 - 
 Mechanizmy przekazywania ciepła                               | m67146 - Tom2, 1.6 - 
 Widma atomowe i promieniowanie rentgenowskie                  | m68256 - Tom3, 8.5 - 
 Wzory matematyczne                                            | m65855 - Tom3, E - 
 Rozkład prędkości cząsteczek gazu doskonałego                 | m67150 - Tom2, 2.4 - 
 Prawo Coulomba                                                | m67162 - Tom2, 5.3 - None
 Dipole elektryczne                                            | m67166 - Tom2, 5.7 - None
 Zastosowania sił i pól magnetycznych                          | m67206 - Tom2, 11.7 - None
 Reguła Lenza                                                  | m67217 - Tom2, 13.2 - 
 Proces adiabatyczny gazu doskonałego                          | m67242 - Tom2, 3.6 - None
 Obliczanie potencjału elektrycznego                           | m67175 - Tom2, 7.3 - None
 Wypadkowa sił i moment sił działających na pętlę z prądem     | m67204 - Tom2, 11.5 - None
 Związek między wielkościami w ruchach obrotowym i postępowym  | m65793 - Tom1, 10.3 - ?
 Zderzenia w wielu wymiarach                                   | m65787 - Tom1, 9.5 - ?
 Wyznaczanie równań ruchu metodą całkowania                    | m65753 - Tom1, 3.6 - ?
 Ruch po okręgu                                                | m63775 - Tom1, 4.4 - ?
 Prawa Kirchhoffa                                              | m67195 - Tom2, 10.3 - None
 Pola magnetyczne i ich linie                                  | m67201 - Tom2, 11.2 - None
 Mikroskopowy model dielektryka                                | m67184 - Tom2, 8.5 - None
 Entropia w skali mikroskopowej                                | m67158 - Tom2, 4.7 - None
 Wyznaczanie natężenia pola elektrycznego rozkładu ładunków    | m67164 - Tom2, 5.5 - None
(27 rows)

**Comment by omehes** [comment]
This issue is still present, notes from slack discussions are in the link:
https://openstax.slack.com/archives/C0LA54Q5C/p1553176578574600

**Comment by openstaxalina** [comment]
I moved this into the Books team backlog; this will be re-tested after https://github.com/openstax/cnx-recipes/issues/726 is complete.

**Comment by brittweinstein** [comment]
@omehes is this fixed on production?

**Comment by brittweinstein** [comment]
@openstaxalina thank you for the clarification!
