### ISSUE TITLE
WEBVIEW PORTION: Change Request: Remove option for module PDFs

### ISSUE THREAD

**Issue by openstaxalina** [openstax/webview#2133]
See description in: https://github.com/Connexions/cnx/issues/38

This card is for the webview portion only.

**Comment by brittweinstein** [comment]
@omehes could you verify that it is on production and close this issue if it is?

**Comment by omehes** [comment]
Verified on staging.cnx.org
Fixed

{"date": "2019-02-19 10:33:39 CST",
 "webview": "6fea2e99064f4522c968ac6b4ada6203d9eb9e5d (v0.46.0)",
 "cnx-archive": "4.10.0",
 "cnx-publishing": "0.15.0",
 "oer.exports": "bomb.blondie v0.72.0",
 "press": "8.0.2",
 "cnx-deploy": "v2.37.1"
}

**Comment by omehes** [comment]
reverified on production. ok

{"date": "2019-02-26 08:48:52 CST",
 "webview": "6fea2e99064f4522c968ac6b4ada6203d9eb9e5d (v0.46.0)",
 "cnx-archive": "4.10.0",
 "cnx-publishing": "0.15.1",
 "oer.exports": "bomb.blondie v0.72.0",
 "press": "8.0.2",
 "cnx-deploy": "v2.37.3"
}
