### ISSUE TITLE
Inconsistent types of lists

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2136]
On katalyst01 (e.g. https://katalyst01.cnx.org/contents/W8wOWXNF@18.8:36iSJo6e@18.8/Review-Questions) lists in **Review Questions** are created in two ways: by `type="a"` and `type="A"`. 

![lists](https://user-images.githubusercontent.com/40228854/49941141-f0738780-fee1-11e8-89dc-6721e7b40c7e.JPG)

In PDF all lists are created in the same way:

![lists_pdf](https://user-images.githubusercontent.com/40228854/49941177-0da85600-fee2-11e8-8189-9e474bc5829e.JPG)

**Comment by openstaxalina** [comment]
It looks like the PDF template is standardizing them, whereas the content is not standardized :-(

@helenemccarron is there any possibility of making lists in review questions in American Government standardize to lowercase?  This would give us some more time to standardize the content.  Let us know your thoughts.  cc @lwtchu @PatBoj

**Comment by PatBoj** [comment]
The question is how this affect other books.
```
.review-questions [type="A"] {
  list-style-type: lower-alpha;
}
```

**Comment by PatBoj** [comment]
@helenemccarron Do you have any idea how to fix that and reduce impact on the other books?

**Comment by helenemccarron** [comment]
In this case, it would affect all books using the `.review-questions` class. @openstaxalina would that be acceptable? I am not sure which books are using that class, maybe the bookmaps could help?

**Comment by PatBoj** [comment]
@helenemccarron I've checked this out and it will affect to _Astronomy_ (ex. https://katalyst01.cnx.org/contents/LnN76Opl@14.24:vkZyi4XZ@14.24/Exercises), _U.S. History_ (ex. https://katalyst01.cnx.org/contents/p7ovuIkl@6.3:oDi6rxmE@6.3/Review-Questions).

**Comment by openstaxalina** [comment]
Thank you so much for that investigatn @PatBoj -- that is super helpful.

We should standardize all lists in .review-questions to uppercase.  My understanding is that this will impact _Astronomy_ and _U.S. History_ , where PDF & Webview will match, and _American Government_, where PDF & Webview will not match, but this is okay (confirmed w/ Anthony).

Please let me know if you have any questions @helenemccarron @Adrianltd @wilkus27.

**Comment by openstaxalina** [comment]
Also, please let me know if this impacts other titles than the three listed above.

**Comment by wilkus27** [comment]
I'm going to check other books by Elefind, but I'm not sure how much time it will takes.

**Comment by openstaxalina** [comment]
This spreadsheet captures which books use `type="A"` and/or `class="review-questions"` https://docs.google.com/spreadsheets/d/1xRt2in0XaFpA5no6yLQbXBf7Q7pKeJ4yzI4yRpFacKY/edit#gid=0

**Comment by openstaxalina** [comment]
Based on the above spreadsheet, this change will also impact Economics textbooks and _Psychology_, which use the review-questions class. However, economics review questions do not contain answer choices, thus are not actually impacted by the change to uppercase letters.  

The _Psychology_ PDF uses lowercase letters, so the change to uppercase in webview will create a discrepancy between PDF and webview, but this is acceptable.

**Comment by openstaxalina** [comment]
Copying the final decision one more time: 

We should standardize all lists in .review-questions to **uppercase**.

(https://github.com/openstax/webview/issues/2136#issuecomment-453203879)

**Comment by wilkus27** [comment]
Verified on katalyst01:

**American Government** - 144 lists from 197 changed
For example:

![am_gov](https://user-images.githubusercontent.com/40228854/51601043-b0052180-1f03-11e9-8968-cbf437e6eb03.JPG)

**Psychology** - 888 lists from 936 changed
For example: (https://katalyst01.cnx.org/contents/Sr8Ev5Og@9.20:xk6LHatM@9.20/Review-Questions)

![psycho](https://user-images.githubusercontent.com/40228854/51601168-ec388200-1f03-11e9-8c2f-7745501bc012.JPG)

**Principles of Macroeconomics for AP Courses 2e** - 2 lists from 2 changed
Only one section with lists: (https://katalyst01.cnx.org/contents/kRfPjKij@6.3:lhrtrQyF@6.3/Review-Questions)

![macro](https://user-images.githubusercontent.com/40228854/51601321-518c7300-1f04-11e9-8c10-57922848c9c5.JPG)

**Principles of Economics 2e** - 2 list from 2 changed
Only one section with lists: (https://katalyst01.cnx.org/contents/vEmOH-_p@6.4:TUKUKoAx@6.4/Review-Questions)

![econ](https://user-images.githubusercontent.com/40228854/51601389-7bde3080-1f04-11e9-9373-a02cca68e423.JPG)

**Comment by openstaxalina** [comment]
Confirmed working correctly in American Government 2e in production webview:
<img width="1205" alt="screen shot 2019-02-13 at 10 56 53 am" src="https://user-images.githubusercontent.com/7863733/52729100-24206b80-2f7e-11e9-8b53-d5d6ae2ae636.png">
