### ISSUE TITLE
NOT DOING NOW Baked Book Changes Don't Show Up on Module Only View

### ISSUE THREAD

**Issue by marcjeannott** [openstax/webview#2151]
While working on a different issue, I noticed that a baked book such as College Physics does not show any baked book stuff when looking at the modules alone. For example, https://staging.cnx.org/contents/CImQfPDv@4.1:lBmVYBst@8/1-3-Add-and-Subtract-Integers
has class has-images in the images of the table, making them big and easy to see, but
https://staging.cnx.org/contents/lBmVYBst@8/Add-and-Subtract-Integers
has that same class, but doesn't show up big and easy to see.

I talked to Alina about this and was asked to open an issue, since ideally we'd want baked stuff to show even if just looking at a module.

**Comment by brittweinstein** [comment]
Could someone please put an estimate on this?

**Comment by brittweinstein** [comment]
Needs more analysis. We will get to this work in a quarter where we are not publishing as much.
