### ISSUE TITLE
Accounting - Exercise listing

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/webview#2152]
content03
GLOBAL

“Exercises” should be singular “Exercise” as in PDF and as with “Problem” sets. Applies to list on left (TOC) and list on right at bottom of opening page.
**Exercise Set A
Exercise Set B**

![exerciseswebview](https://user-images.githubusercontent.com/19212926/50779641-e76e9f80-126e-11e9-82be-405a8d7104b6.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d99e5c63-83cb-48fe-b2e3-a705175bd16d)

**Comment by openstaxalina** [comment]
confirmed fixed in final Managerial Accounting PDF: 
<img width="643" alt="screen shot 2019-02-12 at 11 16 09 am" src="https://user-images.githubusercontent.com/7863733/52654465-a4c86480-2eb7-11e9-9107-d25fe5e9a220.png">
