### ISSUE TITLE
TABLE OVERHAUL Accounting - Table design

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/webview#2154]
content03
GLOBAL

Shading and differentiation of tables with merged cells is problematic re: clarity of content in webview. Webview is assigning same design to merged cells (e.g., Production” and “Purchasing material”). Webview style seems to be driven by smallest factor (right column) instead of pedagogical “chunks” (left column). If “Production” and “Purchasing material” aren’t adequately distinguished in webview, this will be confusing to students. 

Would it be possible to remove the cell shading entirely, and add exterior and interior rules to webview tables? We understand this may be a longer term consideration/fix.

PDF for reference
![pdftable](https://user-images.githubusercontent.com/19212926/50848407-3afded80-1342-11e9-983f-8799b4cbe190.png)

Webview
![webviewtable](https://user-images.githubusercontent.com/19212926/50848416-3cc7b100-1342-11e9-8c51-f50c34cd815c.jpg)

**Comment by openstaxalina** [comment]
Would like to discuss options on Monday with @lwtchu @helenemccarron @brittany-johnson @tomjw64.  Note above request: _Would it be possible to remove the cell shading entirely, and add exterior and interior rules to webview tables? We understand this may be a longer term consideration/fix._

**Comment by tomjw64** [comment]
@openstaxalina @mwest-WWprod Is it possible to get a link to where this happens in webview so that we can get a good look at the markup?

**Comment by openstaxalina** [comment]
@tomjw64, good point :-) 
here you go: https://content03.cnx.org/contents/nBM3VIXy@3.14:4A0nAXdZ@4/6-3-Calculate-Activity-Based-Product-Costs

**Comment by tomjw64** [comment]
We have a couple options here:
1) Checkerboard the merged spans themselves (either with JS or possibly some really complex CSS) (darkened the screenshot for visibility)
Option 1 might looks something like this
![screenshot_9](https://user-images.githubusercontent.com/1285308/51048092-b7394080-158f-11e9-86bc-ff33213da140.png)
2) Use JS to find tables containing merged spans to be styled with borders instead
3) Have content add an attribute to tables that we wish to be styled in this manner and then use the attribute to find such tables to use borders instead
Options 2&3 could look something like this:
![screenshot_10](https://user-images.githubusercontent.com/1285308/51048509-c1a80a00-1590-11e9-8755-81abf271a52e.png)

**Comment by openstaxalina** [comment]
@tomjw64 this is great; I'll go over these options with WiseWire on Tuesday (1/15).

**Comment by brittweinstein** [comment]
@openstaxalina to show visuals of option 1 and 3 to WW on call tomorrow.

**Comment by openstaxalina** [comment]
@mwest-WWprod + team gathering more examples, possibly examples with multiple lines of text in the cell.

@openstaxalina revisit with team -- why aren't the colors alternating on the left side?  Isn't this a fix we would want for all tables?

May need to resolve this post-publication.

**Comment by brittweinstein** [comment]
@openstaxalina should we push this over into bomb.blondie for post publication work?

**Comment by openstaxalina** [comment]
@brittweinstein thank you for following up about this!

Wisewire is going to pursue content fixes for most of these cases, and we are not holding publication for any changes to webview table design.

Wisewire is also going to open a few other issues related to table design in webview.

I will move this into the backlog so we can take a more holistic approach to improving table design when we are not so close to publishing deadlines.

**Comment by openstaxalina** [comment]
Need to fix for fall 2019.

**Comment by openstaxalina** [comment]
We do not plan to use shading as a default/standard in tables going forward.  Shading is not used in the oer.exports PDF templates.  Shading will not be used in the baked styles except possibly at a book-specific level and/or via a class added to that specific table.  

Therefore, we'd like to pursue removing shading entirely from tables in webview.  Need to assess with template devs and Alan about the coding and test load on this.

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/mwjClAV_@8.2:SXjiAlpU@8.2/Key-Equations
Here are equations in tables (reported in issue #916).
1. Do we leave it like this?
2. Is there possibility that table overhaul will effect Key equations in tables?

**Comment by openstaxalina** [comment]
@MartaSztuka thank you for finding this.  Yes, with the new table styling, key equations tables will no longer have shading, but will have vertical and horizontal lines.  This is acceptable from my perspective, but do you foresee problems with this @MartaSztuka ?


cc @lwtchu

**Comment by MartaSztuka** [comment]
@openstaxalina I don't think this will be problem, without shading lines will not disturb. However Table numbering might be misleading in Key Equations.

**Comment by MartaSztuka** [comment]
Tested on Katalyst01
![Screenshot from 2019-06-04 11-47-28](https://user-images.githubusercontent.com/47241114/58869489-9e583580-86be-11e9-8096-a695ceb20e5e.png)
