### ISSUE TITLE
Numbering in section References

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2155]
On katalyst01 (https://katalyst01.cnx.org/contents/W8wOWXNF@18.8:PZqKd1ie@18.8/References) in **References** section numbers should be bolded and after each number should be added the dot. This is how it looks now:

![numbering](https://user-images.githubusercontent.com/40228854/50891566-da7fb680-13fc-11e9-9c0f-cdc1de0dbed7.JPG)

**Comment by PatBoj** [comment]
@wilkus27 It's ready for testing.

**Comment by wilkus27** [comment]
Veryfied on katalyst01:

![numbers](https://user-images.githubusercontent.com/40228854/51379543-f6c3d780-1b0f-11e9-827d-4091fd16066a.JPG)

**Comment by openstaxalina** [comment]
Confirmed appearing correctly in American Government 2e in production webview:
<img width="1281" alt="screen shot 2019-02-13 at 10 54 48 am" src="https://user-images.githubusercontent.com/7863733/52728935-d146b400-2f7d-11e9-96cf-15049e69c42f.png">
