### ISSUE TITLE
Bold and delete newline in LO links

### ISSUE THREAD

**Issue by oscryan** [openstax/webview#2160]
In Accounting on staging in AW the LO links in webview show up as figure links instead of anything else (like LO icon or other class of link). This occurs in every instance of an LO link, everywhere in the book.

https://staging.cnx.org/contents/kg0cimBs@1.78:mqbLq8fR@1.78/Multiple-Choice

<img width="1307" alt="screen shot 2019-01-14 at 11 58 28 am" src="https://user-images.githubusercontent.com/1895432/51130876-b99bd480-17f3-11e9-8385-2b06877f154a.png">

**Comment by brittany-johnson** [comment]
note for brittanyj: add target label for LO in cnx-recipes

**Comment by openstaxalina** [comment]
In Webview, it should say *LO [#.#]*, example
*LO 1.1* The managers of...

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7b276f4e-e2a1-434d-bc24-331ac8da4b3a)

**Comment by openstaxalina** [comment]
confirmed fixed in final Managerial Accounting webview:
<img width="1182" alt="screen shot 2019-02-12 at 11 17 01 am" src="https://user-images.githubusercontent.com/7863733/52654511-bf9ad900-2eb7-11e9-9284-0dd2c2069df2.png">
:
