### ISSUE TITLE
WAITING [content investigation] Table Numbers Not Displaying

### ISSUE THREAD

**Issue by openstaxalina** [openstax/webview#2165]
Location: https://devb.cnx.org/contents/vhdu3531@10.1:L7Q4WVV7@1/Table-Testing 

Table numbers are not displaying, even though the markup does **not** use the unnumbered class or an empty label tag:
<img width="456" alt="screen shot 2019-01-16 at 10 12 12 am" src="https://user-images.githubusercontent.com/7863733/51262427-f690d400-1977-11e9-88bd-e186182e582c.png">

Note that table numbers display in legacy, so this seems to be a webview problem:
<img width="892" alt="screen shot 2019-01-16 at 10 14 16 am" src="https://user-images.githubusercontent.com/7863733/51262453-03152c80-1978-11e9-9f4d-17e70a029082.png">

**Comment by openstaxalina** [comment]
@oscryan could you please test the APUSH content on content05 and verify the table numbers are still not displaying and also which parameter is applied?

**Comment by oscryan** [comment]
at least 3 table numbers are being counted, and only one is not displaying.
https://content05.cnx.org/contents/jvOGfs7d@11.3:GSGluSA3@2/1-12-%F0%9F%94%8E-The-Ratification-Debate-on-the-Constitution has Table 1
https://content05.cnx.org/contents/jvOGfs7d@11.3:7desLfQq@2/1-17-%E2%9C%92%EF%B8%8F-Thomas-Paine-Common-Sense-1776 has table 2 (in the body, not displaying, as it has unnumbered unstyled class, which makes the number not show up, but no empty label, which makes it rev the table count in the module) and table 3 (in the Historical Reasoning questions, displaying).

If the table test module is available on content05 to test other table-numbering scenarios, I can't find it.

**Comment by openstaxalina** [comment]
Okay, thanks @oscryan.  I am not sure why table numbers were not displaying previously - it may have been a quirk of devb.  I am going to close this issue.
