### ISSUE TITLE
Numbering in EOC not aligned w/ ordered lists 

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/webview#2167]
![Screen Shot 2019-01-18 at 12.53.58 PM.png](https://images.zenhubusercontent.com/5b0d6efdd59b032fbd122962/243dbc07-e8ac-4854-a1f2-1b7a5b161751)

**Comment by openstaxalina** [comment]
@brittany-johnson I noticed that the PDF looks the same in this case:
<img width="521" alt="Screen Shot 2019-03-13 at 1 49 09 PM" src="https://user-images.githubusercontent.com/7863733/54306191-d73cae80-4596-11e9-83e5-bee9faca75c4.png">
Could you clarify what change you recommend here?

**Comment by brittany-johnson** [comment]
@openstaxalina I think I may have added this issue during doomsday testing.
I thought that the list should be aligned with the number, but if this is intentional, nevermind 😂

**Comment by openstaxalina** [comment]
Noted and closing; thank you!
