### ISSUE TITLE
Extra space between equations

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2169]
On katalyst01 sometimes there is an extra space between rows in tables created by math.

For example: https://katalyst01.cnx.org/contents/AndhM9Sd@4.13:02l1UzkA@4/1-1-Use-the-Language-of-Algebra

webview:

![big](https://user-images.githubusercontent.com/40228854/51607775-ef3c6e00-1f15-11e9-9d6e-7382286df686.JPG)

PDF:

![big_pdf](https://user-images.githubusercontent.com/40228854/51607786-f6637c00-1f15-11e9-872e-5203804c7a3c.JPG)

This is an example, where tables are displaying correctly: https://katalyst01.cnx.org/contents/AndhM9Sd@4.13:QlYg2VHd@5/1-3-Fractions

webview:

![small](https://user-images.githubusercontent.com/40228854/51607907-4b9f8d80-1f16-11e9-9003-654d52f20b23.JPG)

PDF:

![small_pdf](https://user-images.githubusercontent.com/40228854/51607920-522e0500-1f16-11e9-832e-766c6814871b.JPG)

**Comment by openstaxalina** [comment]
This was resolved in content; closing.
