### ISSUE TITLE
Spacing in tables created by math

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2170]
On katalyst01 there is some problem with spacing in tables created by math:

1. https://katalyst01.cnx.org/contents/AndhM9Sd@4.13:mH2g0CNm@7/1-5-Properties-of-Real-Numbers

![big](https://user-images.githubusercontent.com/40228854/51609178-b3a3a300-1f19-11e9-8967-a7faf6a70065.JPG)

PDF:

![big_pdf](https://user-images.githubusercontent.com/40228854/51609185-bacab100-1f19-11e9-9607-5c9479d57fc7.JPG)

2. The same page

![big2](https://user-images.githubusercontent.com/40228854/51609200-c5854600-1f19-11e9-9145-9a0e3d28e7b2.JPG)

PDF:

![big2_pdf](https://user-images.githubusercontent.com/40228854/51609210-cc13bd80-1f19-11e9-89e0-4d782a355464.JPG)

**Comment by wilkus27** [comment]
There are other issues with similar problem:
- https://github.com/openstax/webview/issues/2169
- https://github.com/openstax/content-managers/issues/432

They could be related.

**Comment by Adrianltd** [comment]
All of those math elements are created with use of dozens of `span` elements. Every span element has it's css, which looks like:

> position: absolute;
> clip: rect(3.142em, 1023.5em, 4.371em, -1000em);
> top: -3.239em;
> left: 0em;

I am not sure how those math elements are created, but it looks like they are set like this in content and CMs have to change the `top` values to move stuff closer to the top.
