### ISSUE TITLE
Implement a scaled-down-30 class that will display art at 30% of the viewport

### ISSUE THREAD

**Issue by openstaxalina** [openstax/webview#2171]
Some images in Accounting are too large in webview, even when scaled down to 60% of the viewport via the scaled-down class.  Therefore, we made a decision to scale down art to 30% of the viewport if it as the scaled-down class.  A few notes:

This should be implemented exactly as with the scaled-down class, except that the art is scaled down to 30% instead of 60%.
This should work on figures and images.
The caption should also be scaled down on figures.

Please see the document [here](https://docs.google.com/document/d/1S3Eeql_Y5vmqQgqTdFX9G8dMXWOmgCSkXSHUJWgiBr8/edit) for more information and links to content that exhibit the issue.

**Comment by brittweinstein** [comment]
This is for all books.

**Comment by tomjw64** [comment]
@brittweinstein @openstaxalina Looks as though the original `scaled-down` class was only added for baked content on webview. Should I allow `scaled-down` for all books as well?

**Comment by openstaxalina** [comment]
@tomjw64 ah, good catch -- no, this should only be for baked content on webview.

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

## scaled-down

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/dc6b194e-c1b2-407f-b372-260f76d902d3)

## scaled-down-30

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/05c6226d-98b7-4cc3-9e02-e8c8b14966dc)
