### ISSUE TITLE
WORK WITH TUTOR TEAM TO PRIORITIZE PheT simulations are too large for the frame and get controls/text shifted

### ISSUE THREAD

**Issue by omehes** [openstax/webview#2174]
Go to College Physics and select chapters 3.2, 2.4, 3.1, and others with sims
Notice that these embedded sims are too large for their frames and have scrollbars. This also causes some text and controls to be shifted or overlapping.
See attached screen shots.

staging.cnx.org in Chrome and FF

Discussed with @edwoodward 

![phet-11](https://user-images.githubusercontent.com/44207656/52226000-67d5ef80-2871-11e9-947c-baf75c624f69.png)

![phet-22](https://user-images.githubusercontent.com/44207656/52226014-6dcbd080-2871-11e9-9411-b55b615175ef.png)

![phet-33](https://user-images.githubusercontent.com/44207656/52226026-76bca200-2871-11e9-8c7b-656eff6b99cc.png)

**Comment by brittweinstein** [comment]
@openstaxalina would this be something TBDs should look into?

**Comment by omehes** [comment]
I have updated this bug with screenshots after staging deploy on 04/02/2019

**Comment by openstaxalina** [comment]
@brittweinstein we can look into this in the next sprint if possible.  We would prioritize this behind technical work related to publishing new titles this quarter.

**Comment by brittweinstein** [comment]
@oscryan please take a look at this content

**Comment by yblock** [comment]
https://app.zenhub.com/workspaces/cnx-team-5af1f4cc12da5e6d74331b60/issues/openstax/content-managers/631

**Comment by openstaxalina** [comment]
@yblock found other examples of sims that only work properly if they are overflowing the feature box.  He will post details below.

**Comment by yblock** [comment]
Locations where the sim is overflowing: 
Chapter 29, Section 1, Figure 29.6 - https://cnx.org/contents/Ax2o07Ul@14.44:xuwQZnCi@9/29-1-Quantization-of-Energy 

Chapter 30, Section 3, Figure 30.21 - https://cnx.org/contents/Ax2o07Ul@14.44:mirSSr3Q@11/30-3-Bohr-s-Theory-of-the-Hydrogen-Atom

Chapter 31, Section 1, Figure 31.7 - https://cnx.org/contents/Ax2o07Ul@14.44:fjWtUHJu@12/31-1-Nuclear-Radioactivity

Chapter 31, Section 2, Figure 31.11 - https://cnx.org/contents/Ax2o07Ul@14.44:Aw83H98P@8/31-2-Radiation-Detection-and-Detectors

Chapter 31, Section 6, Figure 31.29 - https://cnx.org/contents/Ax2o07Ul@14.44:4Stg9XLf@9/31-6-Binding-Energy


This one is not overflowing, but the content is being cut off by the iframe rendering some of the interactivity broken:
Chapter 32, Section 6, Figure 32.28 - https://cnx.org/contents/Ax2o07Ul@14.44:LJeKXQqg@13/32-6-Fission

**Comment by openstaxalina** [comment]
Closing as this book has been QA'd and released in REX.
