### ISSUE TITLE
Remove dots from table

### ISSUE THREAD

**Issue by uskka** [openstax/webview#2175]
Remove dots from this table, so it will look like PDF.
https://katalyst01.cnx.org/contents/FPtK1zmh@12.8:FwQJfRAS@6/28-2-Embryonic-Development

**webview**
![webview kropken](https://user-images.githubusercontent.com/40228918/51983729-c1b56e80-2499-11e9-978e-f9517a01036b.png)

**PDF**
![pdf kropken](https://user-images.githubusercontent.com/40228918/51983730-c2e69b80-2499-11e9-9e50-75334c0c0a9d.png)

**Comment by Adrianltd** [comment]
If that's only one spot with dotted list I think it would be better to add `[data-bullet-style="none"]` to that list in the content.
I can remove those dots, but then it would affect all unordered lists within tables.
@openstaxalina ^

**Comment by openstaxalina** [comment]
@Adrianltd good point - I will move this to the content repo.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #846](https://github.com/openstax/content-managers/issues/846) via [**ZenHub**](https://www.zenhub.com/)
