### ISSUE TITLE
Different types of lists in Review Questions

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2176]
On katalyst01 (e.g. https://katalyst01.cnx.org/contents/5CvTdmJL@5.8:7AAa2Rr2@5.8/Review-Questions) lists in Review Questions have different types:

![lists](https://user-images.githubusercontent.com/40228854/51992107-b1f35580-24ac-11e9-9ea9-79726d30fee2.JPG)

**Comment by wilkus27** [comment]
This problem looks similar to https://github.com/openstax/webview/issues/2136, but in this book there is no `class="review-questions"`, co it should be solved in another way.

**Comment by openstaxalina** [comment]
Is there another class on this content that we could target to make the lists uppercase as in #2136?

**Comment by wilkus27** [comment]
Veryfied on katalyst01 from feature branch.

Lists in Review Questions in Microbiology and in all books from issue https://github.com/openstax/webview/issues/2136 are working properly. I have found only two books which also have class `os-review-questions-container` but they have already had only lists with `type="A"`.
