### ISSUE TITLE
Remove bullet lists from Glossary

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2179]
On katalyst01 (https://katalyst01.cnx.org/contents/5CvTdmJL@5.9:Is5SUXrg@7/E-Glossary) bullet lists should be removed:

![dots](https://user-images.githubusercontent.com/40228854/52051463-f84fbf80-2553-11e9-9f37-794fe345d6aa.JPG)

This is how it looks in PDF:

![dots_pdf](https://user-images.githubusercontent.com/40228854/52051482-030a5480-2554-11e9-8828-3f9b29a740be.JPG)

**Comment by wilkus27** [comment]
@openstaxalina I think this problem could be resolved by content as in case with Preface: https://github.com/openstax/content-managers/issues/500.

**Comment by openstaxalina** [comment]
We can release in Assignable Webview without this adjustment.

**Comment by Adrianltd** [comment]
I could remove those dots for all `ul` elements inside `glossary` as I did for the `preface` here:
https://github.com/openstax/webview/issues/2198
