### ISSUE TITLE
TABLE OVERHAUL Vertical rules in 'fill in data' tables

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/webview#2183]
GLOBAL (identified in Accounting)

Lack of vertical rules in webview makes it difficult for the student user to readily see where they are supposed to populate data in any 'fill in data' tables. In Accounting this occurs in feature boxes and in EOC assessments.

Example from https://cnx.org/contents/kg0cimBs@5.1:uv7SfKcq@5.1/Thought-Provokers
![table_fillindata](https://user-images.githubusercontent.com/19212926/52152256-bef67d00-2643-11e9-8fa0-ba7d0d00d0ab.png)

**Comment by openstaxalina** [comment]
Need to fix for fall 2019. Per Anthony, prioritize above https://github.com/openstax/webview/issues/2184.

**Comment by openstaxalina** [comment]
Related to https://github.com/openstax/webview/issues/2154, we should remove the shading and add vertical rules in all tables in webview.   Need to assess with template devs and Alan about the coding and test load on this.

**Comment by openstaxalina** [comment]
*Need to make sure there is padding on either side of the vertical lines.

**Comment by MartaSztuka** [comment]
Tested on katalyst01.
![Screenshot from 2019-06-04 13-42-02](https://user-images.githubusercontent.com/47241114/58876534-b1730180-86ce-11e9-960e-cdbeca3c70d3.png)
![Screenshot from 2019-06-04 13-43-37](https://user-images.githubusercontent.com/47241114/58876571-cbacdf80-86ce-11e9-8a59-7784781720a0.png)
