### ISSUE TITLE
TABLE OVERHAUL Text wrapping in tables

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/webview#2184]
GLOBAL (identified in Accounting)

Responsive nature of platform makes it so that as a user scales their browser, or zooms in or out, text can crash in tables. 

Example from https://cnx.org/contents/kg0cimBs@5.1:Vja0jJZ-@5.1/Exercises-Set-A 

![text wrapping in tables](https://user-images.githubusercontent.com/19212926/52153837-970a1800-2649-11e9-9f76-54da57f3ccb3.png)

![text wrapping in tables2](https://user-images.githubusercontent.com/19212926/52153849-9f625300-2649-11e9-89e2-bef96fb472df.png)

**Comment by openstaxalina** [comment]
Need to fix for fall 2019.

**Comment by openstaxalina** [comment]
Our solution proposed in https://github.com/openstax/webview/issues/2183 should resolve this.  Adding the vertical rules will result in a clearer delineation between columns, even when the content is zoomed or otherwise scaled.

**Comment by MartaSztuka** [comment]
Tested on katalyst01
![tabl](https://user-images.githubusercontent.com/47241114/58877903-49261f00-86d2-11e9-9b77-a6663e01a859.jpeg)
