### ISSUE TITLE
Answers not inline in Answer Key

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/webview#2190]
On katalyst01 (https://katalyst01.cnx.org/contents/yqV9q0HH@13.3:-MajHA0Y@13.3/Answer-Key) all answers should be inline.

on katalyst it looks like this:
![answers](https://user-images.githubusercontent.com/47241114/52722031-26e58580-2fab-11e9-9ce1-ce33657d4fe6.png)

in PDF like this:
![screenshot from 2019-02-13 15-55-46](https://user-images.githubusercontent.com/47241114/52721582-47611000-2faa-11e9-9529-3873b9720ede.png)

**Comment by openstaxalina** [comment]
@lwtchu What do you think about this?  Is there a reason that the tokens/answers must be vertically stacked instead of inline with each other?

**Comment by lwtchu** [comment]
@openstaxalina theyre in a list with a class where it makes them follow one after the other and inline

**Comment by lwtchu** [comment]
@openstaxalina I can't remember why we did it this way - we can take them out of the lists and make them sit better on webview if that works

**Comment by openstaxalina** [comment]
@lwtchu so in the above example, do 1.116 and 1.117 have different classes?

**Comment by lwtchu** [comment]
@openstaxalina we added a `<list class="circled">` so we wouldn't have to manually bump them around and the token will always be with its answer: https://github.com/openstax/oer.exports/issues/2149

**Comment by openstaxalina** [comment]
This is a complex issue:
Token are either in paragraphs or lists.
Some token lists have the class "circled" to prevent the token being orphaned and its content going to the next line.
We propose leaving this as-is for now.

With Baked PDF, we may be able to standardize this.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/cnx-recipes #1028](https://github.com/openstax/cnx-recipes/issues/1028) via [**ZenHub**](https://www.zenhub.com/)
