### ISSUE TITLE
[tracking for testing only] Longdesc file & link is lost in cnxml --> html transform

### ISSUE THREAD

**Issue by openstaxalina** [openstax/webview#2191]
@brittweinstein commented on [Tue Sep 25 2018](https://github.com/openstax/rhaptos.cnxmlutils/issues/172)

# Scenario
Description 
This collection - https://cnx.org/contents/pkNZr_pp - includes a longdesc description for all three images.  Per Phil S., the longdesc is lost in the cnxml --> html transformation.  We need this to be preserved in the transformation.  It must be accessible by screenreaders.

# Steps to Reproduce

* **Product**: [ ] Tutor   [ ] Concept Coach [ ] OS Web [ ] Content Production Toolkit [x] CNX

* **How many times were you able to reproduce the issue?** Phil S. produced the issue in the content linked above.
* **Images or Screenshots Included:** [ ] Yes  [x] No  (_attach below_)

# Environment:

* **Instance**: [x] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [x] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [x] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [ ] High [x] Medium  [ ] Low
* **Frequency of Occurrence**: [x] High [ ] Medium  [ ] Low

Phil's comment: 
The gist is that we need to:

pass the longdesc="filename.txt" attribute from cnxml into XHTML
treat the longdesc attribute the same way we treat <img src="..."> elements and translate it throughout the epub process

---

@reedstrm commented on [Wed Feb 13 2019](https://github.com/openstax/rhaptos.cnxmlutils/issues/172#issuecomment-463241467)

Work path: this will need two changes: one in `rhaptos.cnxmlutils` (in `cnxml-to-html5.xsl`, probably) to pass through the `longdesc` attribute, just like the `src` attribute (or other image attrs that we copy through). This is XSLT work.

The other change will be in `cnx-epub`, were we convert the filename that was passed through to a `/resources/<sha1>` path served by archive. Again, go looking for what we do for `src` attr. Pretty sure there's a list somewhere of attribute-names-that-are-actually-file-references that get converted at 'storage into the DB time'. This is python work.

---

@reedstrm commented on [Wed Feb 13 2019](https://github.com/openstax/rhaptos.cnxmlutils/issues/172#issuecomment-463245166)

Hmm, slightly more - seems we put `longdesc` on the wrapper `media` element, as well as/instead of on the image, so needs a little more XSLT work to move it to the `img` tag - we do the same thing for `alt` so copying that approach would work.

**Testing**

The easiest way to test this would be to test on autodev01.cnx.org after the code is merged to master. Autodev01 is updated automatically when a PR is merged. We could then republish the [test collection](https://autodev01.cnx.org/contents/pkNZr_pp@2.1:MV7qbhiY@1/Long-Desc-test) and review the HTML for longdesc in the HTML.

**Comment by openstaxalina** [comment]
Decision: Analyze the impact, since this is a transforms change.

**Comment by openstaxalina** [comment]
CNX team (Marvin) will code the fixes, but Books needs to help out with regression testing.

**Comment by Stackblocks** [comment]
- If `longdesc=` was getting lost completely in the transform then it is now present in the markup.
- If `longdesc=` was already showing up in the wrapper and was supposed to be moved onto the `img src=` element then it _is not_ doing that. 
- Either way, the `longdesc=` is rendering the image as "Clickable" in FireFox but interacting with the element does nothing.
