### ISSUE TITLE
Leading is too wide.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/webview#2200]
Wide blank space occurs between lines. (end of subsection)
https://katalyst01.cnx.org/contents/i4nRcikn@3.7:DSFrV7ZX@4/6-1-Areas-between-Curves

PDF: (Bit wider leading is justified by fraction in y=-3/5)
![screenshot from 2019-02-27 12-08-22](https://user-images.githubusercontent.com/47241114/53494869-fae3fd00-3a9e-11e9-81eb-4373bd646ff1.png)

webview: (Here leading is wey to big, second line should be at the top, not half way up the tent)
![screenshot from 2019-02-27 12-08-09](https://user-images.githubusercontent.com/47241114/53494897-0a634600-3a9f-11e9-8b5c-b263017bc78a.png)

Occures once in the book, if not I'll edit issue.

**Comment by wilkus27** [comment]
It looks like that, because figures in Section Exercises display in line with text. 
This problem occurs beacuse release flag `exercise container` wasn't enabled. Now this flag is removed, so I just need to update code with last changes.

I move this issue to cnx-recipes repo.

**Comment by wilkus27** [comment]
Issue moved to [openstax/cnx-recipes #892](https://github.com/openstax/cnx-recipes/issues/892) via [**ZenHub**](https://www.zenhub.com/)
