### ISSUE TITLE
NOT DOING NOW Center unnumbered figures on webview

### ISSUE THREAD

**Issue by uskka** [openstax/webview#2202]
All of the figures in Precalculus that are unnumbered are centered in the PDF, they should be centered on Webview too. 

https://katalyst01.cnx.org/contents/_VPq4foj@8.1:Nis4nvtB@11/1-4-Composition-of-Functions

Webview

![webview](https://user-images.githubusercontent.com/40228918/53498596-e6a3fe00-3aa6-11e9-9fc8-253293985259.png)

PDF

![pdf](https://user-images.githubusercontent.com/40228918/53498598-e73c9480-3aa6-11e9-90ab-c2cf9ac19007.png)

**Comment by Adrianltd** [comment]
Might be related to https://github.com/openstax/webview/issues/2008 but in this case it's not a `figure`, it's an `img`.
If this can be centered without regressions then it's done in: https://github.com/openstax/webview/pull/2206
If should stay as is - please ignore and close the PR.

cc: @openstaxalina

**Comment by openstaxalina** [comment]
@Adrianltd which books does your PR impact?  all images in all books?  or only the books with the precalculus recipe?

**Comment by Adrianltd** [comment]
@openstaxalina That PR will impact all `img` elements (not `figure`) inside `span` elements that have a `data-type="media"` in all books.

**Comment by openstaxalina** [comment]
@Adrianltd I think this is too big a change; I am not sure we want all images centered and this also creates a significant testing load.  Could you close the PR?  Sorry, I didn't see this issue until it was already coded :-(

**Comment by Adrianltd** [comment]
@openstaxalina Sure. Will this be solved in the content (eg. add a class to the images that should be centered)?

**Comment by openstaxalina** [comment]
@Adrianltd I'm not sure yet, but we do have an issue open for this (https://github.com/openstax/cnx-recipes/issues/676) which we are keeping open until we decide how to handle image alignment globally.

**Comment by MartaSztuka** [comment]
Problem is tracked in other issue, can be closed.
