### ISSUE TITLE
Missing table numbering

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/webview#2204]
Table caption does not appear when table is nested in Examples or Exercises. Problem occurs both in PDF and webview.
https://katalyst01.cnx.org/contents/i4nRcikn@3.7:zjNlU1zg@5/4-5-Derivatives-and-the-Shape-of-a-Graph

![tabelki2](https://user-images.githubusercontent.com/47241114/53574877-c50f4900-3b70-11e9-9cce-d2a8bc1f99b1.png)

![tabelki1](https://user-images.githubusercontent.com/47241114/53574889-cb9dc080-3b70-11e9-8374-1b7b635d4288.png)

This issue refers to all tables nested in Examples, some of those in Exercise, and Glossary.
This occurs exerywhere book has tables in Examples #.#; Pdf 'counts' them, but doesn't show captions, webview 'ignores' them. Either way it's missleading and should be fixed I think both in pdf and webview.

**Comment by wilkus27** [comment]
@openstaxalina I remember there was a similiar issue in Phase 1, but I couldn't find it. I think it is content releated. I mean, the problem with PDF, where all tables are counted, even those with `class="unnumbered"`.

**Comment by openstaxalina** [comment]
@wilkus27 I remember now - we had this issue with DevMath and we were able to adjust the PDFs between semesters.  We may be able to do something similar for Calculus - I am investigating.

**Comment by MartaSztuka** [comment]
@openstaxalina I've tracked the table issue in Calculus vol.1, here's table of tables: https://docs.google.com/spreadsheets/d/18XOAAwOY8ZPbyf4zdF9Pt49rxfqK8qGDifvhw2kVV0k/edit#gid=0
