### ISSUE TITLE
No scroll bar on Mac OS

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/webview#2210]
On Mac OS Safari there's no scroll bar under Table 4.7
https://katalyst01.cnx.org/contents/i4nRcikn@3.7:u24zPEAt@10/4-8-L-H%C3%B4pital-s-Rule

![suwak](https://user-images.githubusercontent.com/47241114/53819521-5e23d280-3f6a-11e9-80ae-90b7c20907af.png)

It happens because Safari doesn't support attribute/badge? overflow-x: auto.

**Comment by wilkus27** [comment]
Issue couldn't be reproduce.

**Decision:** close the issue.
