### ISSUE TITLE
How to make staging deployment (less) error prone  

### ISSUE THREAD

**Issue by omehes** [openstax/webview#2211]
We need to discus and document better and safer ways to deploy to staging:
- we need to make staging deployment more error safe
- make sure that steps and dependencies are not omitted causing (multiple) re-deployments and delaying regression tests  
- and if possible, automate some part of the deployment process

**Comment by brittweinstein** [comment]
Issue moved to [openstax/cnx #258](https://github.com/openstax/cnx/issues/258) via [**ZenHub**](https://www.zenhub.com/)
