### ISSUE TITLE
Equations & Sentences outside the frame

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/webview#2212]
Ends of equations and sentences doesn't fit the frame when ToC is opened.
https://katalyst01.cnx.org/contents/i4nRcikn@3.7:056cQH8B@7/1-2-Basic-Classes-of-Functions

![screenshot from 2019-03-06 17-16-07](https://user-images.githubusercontent.com/47241114/53896720-dbb41500-4034-11e9-91ea-a0b9d9f6177c.png)

All locations where problem occurs is in the table:
https://docs.google.com/spreadsheets/d/1SsZ7rZ5fgliuN9ICqHS3FuwwxCEnUf8GW4mpS7c96tY/edit#gid=0

**Comment by MartaSztuka** [comment]
@lwtchu Location list of issues for vol. 2 is ready, most probably tommorow I'll finish vol. 3

**Comment by openstaxalina** [comment]
@MartaSztuka could you let us know when the location list is ready for volumes 1, 2, and 3?  (Also -do you have access to [this folder](https://drive.google.com/drive/folders/0AG1Lx6Hi-6CDUk9PVA) to move the document there?  If not, please let us know.)

**Comment by MartaSztuka** [comment]
@openstaxalina I've moved the file to Openstax Joint Project,
Will finish vol.3 as soon as possible

**Comment by MartaSztuka** [comment]
@openstaxalina Took a while, but table vol.3 is ready

**Comment by openstaxalina** [comment]
@MartaSztuka thanks!  We'll take it from here 👍

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #688](https://github.com/openstax/content-managers/issues/688) via [**ZenHub**](https://www.zenhub.com/)
