### ISSUE TITLE
Odd bracket in Try it.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/webview#2214]
In webview bracket is added to equation.
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:GDS8ZHCU@10/1-3-Radicals-and-Rational-Exponents

![nawias](https://user-images.githubusercontent.com/47241114/54027377-9eb96100-41a1-11e9-8d3a-324a8a43c254.jpeg)

*despite numbering differences equations should be the same*

**Comment by openstaxalina** [comment]
This needs to be adjusted in content; moving there.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #666](https://github.com/openstax/content-managers/issues/666) via [**ZenHub**](https://www.zenhub.com/)
