### ISSUE TITLE
Bolded links

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2215]
On katalyst01 in Examples and Checkpoint notes links to the figures and tables are bolded.

**Example**
In Examples it appears just in the part with problem describing:
https://katalyst01.cnx.org/contents/i4nRcikn@3.7:fP4FUrwS@7/1-1-Review-of-Functions

![example_problem](https://user-images.githubusercontent.com/40228854/54139420-cd456f00-4421-11e9-8aa3-9727d648779b.JPG)

In part with solution it displays without bold:
https://katalyst01.cnx.org/contents/i4nRcikn@3.7:dKCfyV9u@5/2-2-The-Limit-of-a-Function

![example_solution](https://user-images.githubusercontent.com/40228854/54139585-2dd4ac00-4422-11e9-8150-b8deecd51c91.JPG)

**Checkpoint**

https://katalyst01.cnx.org/contents/i4nRcikn@3.7:dKCfyV9u@5/2-2-The-Limit-of-a-Function

![checkpoint](https://user-images.githubusercontent.com/40228854/54139685-683e4900-4422-11e9-94b7-b5cd203ead05.JPG)

**Comment by wilkus27** [comment]
@openstaxalina Bold should be set for links from other parts or removed from Examples and Checkpoints?

**Comment by openstaxalina** [comment]
@wilkus27 bolding should be removed from Examples and Checkpoints; this will achieve consistency within the titles and across other titles.

**Comment by uskka** [comment]
Looks good. Tested on katalyst01.
<img width="854" alt="Screenshot 2019-04-04 at 13 33 07" src="https://user-images.githubusercontent.com/40228918/55552666-42812880-56de-11e9-99b9-0a547cb38da8.png">
<img width="853" alt="Screenshot 2019-04-04 at 13 30 06" src="https://user-images.githubusercontent.com/40228918/55552719-765c4e00-56de-11e9-9dc2-e4b5a2868d79.png">
