### ISSUE TITLE
Inline equations in new line

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2216]
On katalyst01 (e.g. https://katalyst01.cnx.org/contents/i4nRcikn@3.7:blZd_oDf@5/1-3-Trigonometric-Functions) sometimes inline equations display separately in new line:

![inline](https://user-images.githubusercontent.com/40228854/54189164-830bce80-44b1-11e9-853d-fcaa6b619fdf.JPG)

This is how it looks in PDF:

![inline_pdf](https://user-images.githubusercontent.com/40228854/54189181-8e5efa00-44b1-11e9-94bc-f3783ac41c7c.JPG)

**Comment by openstaxalina** [comment]
Is this a bug?  It looks like the math is tagged to be inline:
<img width="1332" alt="Screen Shot 2019-03-13 at 1 55 02 PM" src="https://user-images.githubusercontent.com/7863733/54306592-ac068f00-4597-11e9-8c0d-65df019150bf.png">

**Comment by wilkus27** [comment]
This problem occurs also in unbaked raw-html file. Equation is in new line, because it is in separate `<p>`. I think it is a content issue.  cc @openstaxalina 

![equation](https://user-images.githubusercontent.com/40228854/55079871-5654db00-509d-11e9-85d4-fe0bd5a8992f.png)

**Comment by openstaxalina** [comment]
@wilkus27 thank you for the investigation!  I will move this to the content managers repo so that inline math in separate paragraphs can be taken out of those separate paragraphs.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #695](https://github.com/openstax/content-managers/issues/695) via [**ZenHub**](https://www.zenhub.com/)
