### ISSUE TITLE
Figure in list

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2217]
On katalyst01 (https://katalyst01.cnx.org/contents/i4nRcikn@3.7:Ib8OK9lb@6/1-4-Inverse-Functions) there is an instance when image displays inline with list item:

![fig_list](https://user-images.githubusercontent.com/40228854/54192859-2f9d7e80-44b9-11e9-901e-ba31cf594323.JPG)

`a.` and `b.` should be above the images. At this moment this is the only one such case.

That's how it looks in PDF:

![fig_list_pdf](https://user-images.githubusercontent.com/40228854/54192948-5eb3f000-44b9-11e9-8109-12a49775c721.JPG)

@openstaxalina Should it also be repaired in content?

**Comment by openstaxalina** [comment]
@wilkus27 we do not have to exactly match the behavior of the PDF in this case.  Are there inconsistencies with how images in lists are handled **_within this book in webview_**?  (If so, we may want to address those.)

**Comment by uskka** [comment]
There are no more lists like this in this book in webview. But there are lists like this where after a. , b. there is a text and these lists have the letter and caption above the figure like in the screenshot attached. Example 1.28 https://katalyst01.cnx.org/contents/i4nRcikn@4.1:Ib8OK9lb@6/1-4-Inverse-Functions
<img width="630" alt="Screenshot 2019-04-04 at 16 05 41" src="https://user-images.githubusercontent.com/40228918/55562089-93e7e280-56f3-11e9-8b0a-2a1319df3256.png">

**Comment by openstaxalina** [comment]
Confirmed this is also how this content appears in PDF; therefore, I am closing this issue as resolved.

<img width="535" alt="Screen Shot 2019-04-04 at 11 47 29 AM" src="https://user-images.githubusercontent.com/7863733/55573403-7dc82b00-56cf-11e9-83d7-2678d5193685.png">
