### ISSUE TITLE
Analysis subtitle in Example

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2218]
On katalyst01 (e.g. https://katalyst01.cnx.org/contents/i4nRcikn@3.7:jSsxLwzE@4/2-5-The-Precise-Definition-of-a-Limit) subtitle **Analysis** in Examples notes should be bolded.

webview:

![analysis_bold](https://user-images.githubusercontent.com/40228854/54197933-814c0600-44c5-11e9-9c15-368686ae6cb1.JPG)

PDF:

![analysis_bold_pdf](https://user-images.githubusercontent.com/40228854/54197940-87da7d80-44c5-11e9-87ec-512532812157.JPG)

**Comment by openstaxalina** [comment]
Can these be targeted using `data-type="title"`?
![Screen Shot 2019-03-25 at 1 27 15 PM](https://user-images.githubusercontent.com/7863733/54944545-be6eba00-4f01-11e9-974e-7d2d96d67397.png)

**Comment by openstaxalina** [comment]
If markup is inconsistent, we need to standardize the markup for the Analysis header in Examples.

**Comment by wilkus27** [comment]
Will be resolved in recipes. I move it to this repo.

**Comment by wilkus27** [comment]
Issue moved to [openstax/cnx-recipes #974](https://github.com/openstax/cnx-recipes/issues/974) via [**ZenHub**](https://www.zenhub.com/)
