### ISSUE TITLE
Attribution Tab Shows Markup for PAGES in Baked Books

### ISSUE THREAD

**Issue by openstaxalina** [openstax/webview#2219]
@TomWoodward noticed this.  
Here is a place where this occurs: https://cnx.org/contents/Sr8Ev5Og@10.16:6HoLG-TA@10/Introduction
(Scroll down, select the "Attribution" tab, and select "Page" on the right)
![image](https://user-images.githubusercontent.com/7863733/54212446-efd29900-44b0-11e9-92c8-6df581151540.png)

Note from @reedstrm - BTW, this should be a simple case of adding extra curly braces in the right template in webview. Probably something like `{{title}}` being replaced with `{{{title}}}`

**Comment by brittany-johnson** [comment]
![Screen Shot 2019-03-27 at 6 22 43 PM](https://user-images.githubusercontent.com/24909007/55119078-8660a600-50be-11e9-8c88-525639223025.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8b5aa823-fcb1-420c-bfaa-8e8fa57f57d1)
