### ISSUE TITLE
Coverage While Britt Is Out

### ISSUE THREAD

**Issue by openstaxalina** [openstax/webview#2220]

**Comment by openstaxalina** [comment]
*Monday, March 18*
staging deploy
Alina and Bey coordinating to request from DevOps

*Cards scrums, meetings, retros, planning*
Alina covering for Britt

*Monday, March 25*
Alina to present quarterly progress to Leadership; Britt updating quarterly deliverables document before leaving

*Katalyst Meetings* 
Helene leading these while Britt is out

*Hullabaloo*
Larissa, Helene, Britt meet

**Comment by brittweinstein** [comment]
Staging Deploy for 3/18/19 card: https://trello.com/c/tz9DIbkt/284-cnxbooks-deploy-to-staging-servers-for-20180318-release 

Production Deploy for 3/26/19 card: https://trello.com/c/gAShTqk2/283-cnxbooks-deploy-to-production-servers-for-20190326-release 

Staging Deploy for 4/01/19 card: https://trello.com/c/drXKiO1k/285-cnxbooks-deploy-to-staging-servers-for-20180401-release
