### ISSUE TITLE
Missing Sequence

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/webview#2224]
In College Algebra PDF, Chapter 9, 9.3. Geometric Sequence. 
![pdfakp](https://user-images.githubusercontent.com/47241114/54368199-fe1ce280-4673-11e9-96f1-9d4aba5e2c67.jpeg)

**Comment by brittweinstein** [comment]
This is likely a known issue due to the XYZ redesign but I will ask @marcjeannott to confirm.

**Comment by openstaxalina** [comment]
Yes, this is a known issue; this will be resolved next time we update the _College Algebra_ PDF using the baked styles and the webview source content.
