### ISSUE TITLE
Book/Page buttons do not show clicked status

### ISSUE THREAD

**Issue by openstaxalina** [openstax/webview#2226]
@omehes commented on [Mon Mar 25 2019](https://github.com/openstax/cnx/issues/309)

Steps:
1. open University Physics vol 1 book
2. Click on Chapter Review in Contents
3. Click on any sub-chapter under Chapter Review
4. Scroll down to Downloads, History, Attribution, More Information tabs
5. Click on any of them
6. In the open tab, click on Book/Page buttons
Expected Result: The button should show the clicked state by getting a different colour (grey) and unclicked status with white fill
Actual result: 
1. Once you clicked on any tab and it opens its content, both buttons appear to be white, whereas the Books button should have a grey fill by default (like in other chapters)
2. When you click on Book and then Page buttons, only the Book button gets grey fill. See the screenshot.

{"date": "2019-03-20 15:36:05 CDT",
 "webview": "6402e50a45792a3ce1cc8479eddc9e70f8685e39 (v0.48.0)",
 "cnx-archive": "4.11.0",
 "cnx-publishing": "0.16.2",
 "oer.exports": "crusty.cronut v0.73.0",
 "press": "8.0.2",
 "cnx-deploy": "v2.38.7"
}

![button-notHOT.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/46a7493a-414a-4e94-8397-2fbc8dd9efeb)

**Comment by brittweinstein** [comment]
@openstaxalina is this ready to be tested?

**Comment by openstaxalina** [comment]
@brittweinstein I don't think so - this is still in the Textbook Devs' Backlog and I do not see a PR for this.

**Comment by Adrianltd** [comment]
This bug exists on whatever `ChapterCompositePage` in any book. 
This bug exists after the page content loads (if you try to click on that buttons before the content loads, it works)

There's a part of code in `toggle-partial.html` which probably is not working in those cases:
>  <button class="btn {{#is mediaType 'application/vnd.org.cnx.module'}}active{{/is}}" data-media="page" data-l10n-id="textbook-view-page-button">Page</button>

@helenemccarron or @philschatz any ideas on that?
