### ISSUE TITLE
Line break in exercises

### ISSUE THREAD

**Issue by uskka** [openstax/webview#2228]
There is a line break after the exercise number on webview but it only appears on Safari and in exercises that start with equation and there is a figure after it. 

https://katalyst01.cnx.org/contents/HTmjSAcf@3.4:DSFrV7ZX@5/2-1-Areas-between-Curves
https://katalyst01.cnx.org/contents/oxzXkyFi@3.7:9fEOYsBF@8/3-3-Arc-Length-and-Curvature

Webview
<img width="909" alt="Screenshot 2019-03-28 at 10 12 12" src="https://user-images.githubusercontent.com/40228918/55148229-1bf44800-5148-11e9-8fca-e9bad85b0b4c.png">

PDF
<img width="1309" alt="Screenshot 2019-03-28 at 10 12 20" src="https://user-images.githubusercontent.com/40228918/55148230-1bf44800-5148-11e9-97ff-24c35438a7e7.png">

**Comment by wilkus27** [comment]
After discussion in https://github.com/openstax/webview/pull/2239#issuecomment-482634139 decision is to not fix this issue.
