### ISSUE TITLE
Accessibility: Add Text to Show Solution Button

### ISSUE THREAD

**Issue by openstaxalina** [openstax/webview#2229]
Report received from the IT Dept of Lakeland CC:

_The OpenStax site is pretty good, although 49 errors there are really only 3 issues, and if the “show Solution” button had the text on it that would really take care of 47 of them._

![pastedImagebase640](https://user-images.githubusercontent.com/7863733/55186694-2d981880-5165-11e9-99df-2a8f95eabca7.png)

The requested change is to add text on the Show Solution button, as it appears in the Check Your Understanding features at the end of this module: https://cnx.org/contents/Ax2o07Ul@14.79:EC6WBNqn@10/1-2-Physical-Quantities-and-Units

**Comment by openstaxalina** [comment]
(Note for Alina to follow up with Nicole on the email thread "OpenStax Accessibility" when this is resolved.)

**Comment by wilkus27** [comment]
@openstaxalina I can't reproduce this issue. This is how it looks for me in **College Physics** (I used link from above)

![college-physics](https://user-images.githubusercontent.com/40228854/58170648-410ebe00-7c94-11e9-994f-1a5230cd2df7.png)

It acts the same in **Calculus** on production (https://cnx.org/contents/i4nRcikn@5.2:-xC--8XH@10/The-Limit-Laws)

![calculus-prod](https://user-images.githubusercontent.com/40228854/58170890-f5a8df80-7c94-11e9-9499-5cfe3c8627ec.png)

Also in the baked book on katalyst01 (https://katalyst01.cnx.org/contents/i4nRcikn@4.1:-xC--8XH@9/2-3-The-Limit-Laws)

![calculus-kat](https://user-images.githubusercontent.com/40228854/58170987-34d73080-7c95-11e9-90c6-bae0006f6162.png)

Veryfied also on mac:

<img width="1440" alt="calc-mac" src="https://user-images.githubusercontent.com/40228854/58171075-664ffc00-7c95-11e9-830d-f2858d35e50c.png">

**Comment by wilkus27** [comment]
@openstaxalina I analized it and I think that such solution can be done in content. I have found that adding `aria-label` attribute to `<button>` tag also can help. I tried to do this manually on the page and then run Wave. After that there were no more error in this place which I changed,  but I don't know if it's a good solution. Attribute can be added in content or in JS, but I'm not familiar with that. @Adrianltd @helenemccarron please give me your thoughts, maybe there is another option to fix that problem.

**Comment by Adrianltd** [comment]
I think that adding `aria-label` is best for accessibility. It proably can be added with JS or recipes, that we still would need adding a class to that button in the content, so it will be much easier to just add that aria-label in the content.
There is already `aria-label="show-solution"` and `aria-label="hide-solution"` added to the parent element, but `button` should also contain that label.
