### ISSUE TITLE
Text Should Not Wrap Around Images

### ISSUE THREAD

**Issue by Adrianltd** [openstax/webview#2232]
@MartaSztuka commented on [Mon Mar 11 2019](https://github.com/openstax/cnx-recipes/issues/913)

https://katalyst01.cnx.org/contents/mwjClAV_@8.1:z1lgUlD3@8.1/Chapter-3

![ukłądrownan](https://user-images.githubusercontent.com/47241114/54125880-7bdbb680-4406-11e9-83ad-55a936088695.jpeg)

---

@openstaxalina commented on [Wed Mar 13 2019](https://github.com/openstax/cnx-recipes/issues/913#issuecomment-472516955)

 **I think that we should remove text wrapping around images.**

**Comment by MartaSztuka** [comment]
Tested on katalyst01, all 3 books are fixed.
@openstaxalina Can I close the issue?
![Screenshot from 2019-04-04 14-04-00](https://user-images.githubusercontent.com/47241114/55554505-39468a80-56e3-11e9-91bd-28f8a9b1c521.png)

**Comment by openstaxalina** [comment]
@MartaSztuka yes, I agree this can be closed.  Thank you!
