### ISSUE TITLE
Leading between number and answer in Key.

### ISSUE THREAD

**Issue by Adrianltd** [openstax/webview#2234]
@MartaSztuka commented on [Tue Mar 12 2019](https://github.com/openstax/cnx-recipes/issues/920)

https://katalyst01.cnx.org/contents/E6wQevFf@11.1:-S_QNurU@11.1/Chapter-1
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:UZVwLjju@8.1/Chapter-1
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:t6htDPpE@8.1/Chapter-8
In all 3 books leadings in Answer Key is messy
![lead](https://user-images.githubusercontent.com/47241114/54196629-2cf35700-44c2-11e9-890c-d71a4d379e12.jpeg)

**Comment by MartaSztuka** [comment]
Issue fixed, tested on katalyst01
![Screenshot from 2019-04-03 14-37-30](https://user-images.githubusercontent.com/47241114/55479301-13a37d80-561e-11e9-8562-116c189ed8a4.png)
