### ISSUE TITLE
Credit caption in intro

### ISSUE THREAD

**Issue by Adrianltd** [openstax/webview#2237]
@MartaSztuka commented on [Fri Mar 15 2019](https://github.com/openstax/cnx-recipes/issues/944)

https://katalyst01.cnx.org/contents/mwjClAV_@8.1:MxXhGPWL@5/Introduction-to-Analytic-Geometry
https://katalyst01.cnx.org/contents/_VPq4foj@8.1:viAMjaPp@3/Introduction-to-Exponential-and-Logarithmic-Functions
https://katalyst01.cnx.org/contents/E6wQevFf@11.1:nU8Qkzwo@5/Introduction-to-Prerequisites
![bull](https://user-images.githubusercontent.com/47241114/54418733-0d4c7080-4706-11e9-8eac-78b392e46e9d.jpeg)

---

@openstaxalina commented on [Fri Mar 15 2019](https://github.com/openstax/cnx-recipes/issues/944#issuecomment-473284297)

We decided to unnumber the first image in every chapter; this was the best way to re-start the numbering with subsequent sections while minimizing the test load and changes.

**However, I agree that the caption should not be stacked vertically like it is now.  Can this be fixed so that the caption goes the width of the figure?**

---

@MartaSztuka commented on [Fri Mar 29 2019](https://github.com/openstax/cnx-recipes/issues/944#issuecomment-477667193)

It's fixed now, I'm closing.
![Screenshot from 2019-03-28 17-17-58](https://user-images.githubusercontent.com/47241114/55174337-8d022280-517d-11e9-8a1c-d7deb0d7c3bc.png)

---

@MartaSztuka commented on [Tue Apr 02 2019](https://github.com/openstax/cnx-recipes/issues/944#issuecomment-478884086)

The issue is back.
I really don't know why
But I open it.
![Screenshot from 2019-04-02 09-38-17](https://user-images.githubusercontent.com/47241114/55384971-60a72700-552c-11e9-816e-d729eef2f4c6.png)
![Screenshot from 2019-04-02 09-37-57](https://user-images.githubusercontent.com/47241114/55384974-6270ea80-552c-11e9-9677-4e2d08a390f3.png)
![Screenshot from 2019-04-02 09-37-35](https://user-images.githubusercontent.com/47241114/55384979-64d34480-552c-11e9-8a9f-eea70dc10149.png)

**Comment by MartaSztuka** [comment]
Look's good in all 3 books, tested on katalysty01
![Screenshot from 2019-04-05 12-52-07](https://user-images.githubusercontent.com/47241114/55622982-fa2b3e80-57a1-11e9-8d5b-b80f47292b2a.png)

**Comment by openstaxalina** [comment]
I agree this looks good @MartaSztuka.
