### ISSUE TITLE
[CONTENT INVESTIGATION] Figures are scaled too small in College Physics for AP Courses

### ISSUE THREAD

**Issue by yblock** [openstax/webview#2240]
In College Physics for AP courses, the figures are scaled too small resulting in an odd look and squished figure text. I do not see any classes applied to them other than the main os-figure class which is on all of them. 

https://cnx.org/contents/jQSmhtXo@21.1:L4pdOADV@6/1-1-Physics-An-Introduction 

@helenemccarron

**Comment by brittweinstein** [comment]
assigning to @openstaxalina for prio

**Comment by yblock** [comment]
The images are small because the width and/or height is defined in markup.
