### ISSUE TITLE
Table overlaps text in PDF

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/webview#2241]
https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/CollegeAlgebra-OP_s3hAxEt.pdf
![overlap](https://user-images.githubusercontent.com/47241114/55725395-e257f280-5a0d-11e9-9c97-42bd40f1c68f.jpeg)
I checked on downloaded PDF and on openstax.com, haven't seen anything like this in other places.

**Comment by openstaxalina** [comment]
This is a known issue; this will be fixed next time we update the _College Algebra_ PDF using the baked styles and the webview source.
