### ISSUE TITLE
Figure caption goes down after click

### ISSUE THREAD

**Issue by uskka** [openstax/webview#2245]
Figure caption moves down each time there is a click outside the browser window. I did not figured out the pattern in which figures it appears but it is rare to find figures with this bug.  It appears only on Safari, and I found it so far in Precalculus only. 

Figure 2,5
https://katalyst01.cnx.org/contents/_VPq4foj@8.4:HY2ubE-L@12/1-5-Transformation-of-Functions

Figure 13,14,15
https://katalyst01.cnx.org/contents/_VPq4foj@8.4:HKkfLPmJ@7/1-2-Domain-and-Range

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40228918/55888539-d310aa80-5baf-11e9-9ca5-875f24af46ce.gif)

**Comment by Adrianltd** [comment]
I can't replicate the bug on my computer (system: ubuntu, browser: firefox and chrome).
Any other Mac user can verify that this exists and maybe say more about this?

**Comment by Adrianltd** [comment]
@openstaxalina @helenemccarron I think you're the Mac users :apple:

**Comment by helenemccarron** [comment]
I can confirm it's happening for me as well in Safari. It looks like some of the scripts linked to mouse movements are firing when they shouldn't. @brittany-johnson might have an idea as well.

**Comment by brittany-johnson** [comment]
I can also confirm that it is only happening on Safari, not Chrome or Firefox on Mac. 
I'll try to find a solution.

**Comment by brittany-johnson** [comment]
Just to note: This is also occurring on prod 
https://cnx.org/contents/_VPq4foj@10.3:HY2ubE-L@13/Transformation-of-Functions
