### ISSUE TITLE
Note titles are forcing allcaps in College Algebra

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2256]
@oscryan commented on [Thu May 30 2019](https://github.com/openstax/cnx-recipes/issues/1106)

# What happened?

The whole titles of notes in College Algebra are being capitalized, including variables which must be lowercase,
THUS COMPROMISING PEDAGOGY
*pushes glasses up nose* -@lwtchu
# Reproducibility Details

- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: everywhere

# Environment:

- **Book(s)**: College Algebra
- **URL/Server**: https://staging.cnx.org/contents/mwjClAV_@12.1:_tqWoaDz@19/6-7-Exponential-and-Logarithmic-Models
- **Location (page number, chapter/section)**: notes
- **Suggested nearby searchable text**: characteristics
- **Browser**: Firefox

# Screenshots

<img width="1005" alt="Screen Shot 2019-05-30 at 12 54 23 PM" src="https://user-images.githubusercontent.com/1895432/58653202-cddffa00-82da-11e9-8941-4e1c3a34fde5.png">

---

@wilkus27 commented on [Fri May 31 2019](https://github.com/openstax/cnx-recipes/issues/1106#issuecomment-497756139)

Could be resolved on webview. Move to this repo.

**Comment by openstaxalina** [comment]
@wilkus27 thank you!  Since we are fixing this in webview, are all <note> titles across all titles affected by this change?  Would the content itself dictate the capitalization rather than forcing everything to al caps?

**Comment by wilkus27** [comment]
@openstaxalina changes which I proposed will affect all books, also unbaked. But I'm changing only titles of notes which include `<em>` elements with `[data-effect="italics"]`. 
This is how it will display:

![image](https://user-images.githubusercontent.com/40228854/58796407-79e85480-85fd-11e9-8e8c-059d8a2600ee.png)

All words in title will be forcing to all caps as previously, but the capitalization of `<em>` elements will be dictated by content.

**Comment by openstaxalina** [comment]
The most semantic solution would be to encode this as MathML rather than using emphasis tags.  Need to discuss pros/cons and feasibility with the content managers.

**Comment by oscryan** [comment]
we have definitely used mathml in note titles before

**Comment by wilkus27** [comment]
@openstaxalina When I was doing a research I've found that similar issue appears also in other books, e.g in dev-math and college physics. To find those instances in baked books I put in Elefind (https://content-finder.herokuapp.com/) such selector: `[data-type="note"] .os-title [data-effect="italics"]`

**Comment by openstaxalina** [comment]
@wilkus27 thank you!  That is a way that we could find all these instances @oscryan. 

Transferring this to Content Managers repo.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/content-managers #866](https://github.com/openstax/content-managers/issues/866) via [**ZenHub**](https://www.zenhub.com/)
