### ISSUE TITLE
Leading is too wide.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/webview#2258]
https://katalyst01.cnx.org/contents/AndhM9Sd@6.1:02l1UzkA@17/1-1-Use-the-Language-of-Algebra

Text display weirdly in the table, which is misleading. This issue occurs only here.
![leading](https://user-images.githubusercontent.com/47241114/59199837-3494cb80-8b97-11e9-8f9f-aa6ea78d2ca5.jpeg)

**Comment by brittweinstein** [comment]
@marcjeannott please take a look at the content and fix this if possible. If this is not a content error, please assign to @wilkus27 .

**Comment by marcjeannott** [comment]
<entry valign="top" align="left">the quotient of <m:math><m:mi>a</m:mi></m:math> and <m:math><m:mrow><m:mi>b</m:mi><m:mo>;</m:mo></m:mrow></m:math><newline/><m:math><m:mi>a</m:mi></m:math> is called the dividend, and <m:math><m:mi>b</m:mi></m:math> is called the divisor</entry>

There's a newline. I don't know why it's being transformed that way. (I thought there was a related issue to this a long time ago?)

**Comment by brittweinstein** [comment]
@helenemccarron could this be a transforms issue?

**Comment by helenemccarron** [comment]
I would look at whether the server is up to date compared CNX. It looks like it works on production. It does look like the transforms issue that has been plaguing us.

**Comment by brittweinstein** [comment]
@marcjeannott  could you ensure that the content (CNXML) is the same on the katalyst server and the production server?

**Comment by marcjeannott** [comment]
Updated my comment the one above is Katalyst this one is Production. It's the same CNXML

`the quotient of <m:math><m:mi>a</m:mi></m:math> and <m:math><m:mrow><m:mi>b</m:mi><m:mo>;</m:mo></m:mrow></m:math><newline/><m:math><m:mi>a</m:mi></m:math> is called the dividend, and <m:math><m:mi>b</m:mi></m:math>`

**Comment by brittweinstein** [comment]
@helenemccarron the content is the same and I assume this is a transforms issue. I will put this in Leaky Pipes to keep an eye on it after all of the transforms work is done.

**Comment by brittweinstein** [comment]
we will be able to verify this after our test fest! @openstaxalina @marcjeannott

**Comment by brittweinstein** [comment]
8/10 Decision: Closing b/c this has been released in REX.
