### ISSUE TITLE
Unevenly crossed lines in tables.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/webview#2260]
https://katalyst01.cnx.org/contents/b0yPizXD@2.1:aSsMehg7@1/Word-games
Lines in tables are like not styled all over the book. In several locations doesn't cross properly.
![lines](https://user-images.githubusercontent.com/47241114/59496862-9f455000-8e92-11e9-8513-771b76ed4b27.jpeg)

**Comment by brittweinstein** [comment]
assigning to @openstaxalina for prio

**Comment by openstaxalina** [comment]
I believe this is occurring because this is a single table with differing numbers of cells in the rows. 
I believe the content creator would need to correct this in the content.  I am going to close this.
