### ISSUE TITLE
Unnecessary cells.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/webview#2261]
https://katalyst01.cnx.org/contents/b0yPizXD@2.1:rOr6L5qs@1/Listening-skills-and-tongue-twisters
![tab cells](https://user-images.githubusercontent.com/47241114/59501752-7aee7100-8e9c-11e9-9673-79c2e5b23db8.jpeg)

Most of tables in the book are like this.

**Comment by brittweinstein** [comment]
This is a content fix. I don't think we should fix it but will leave it for @openstaxalina to decide.

**Comment by openstaxalina** [comment]
Since this is not an OpenStax book, we will not make this fix.  The content creator will be able to make this fix in content if desired.
