### ISSUE TITLE
Text is sticking to table lines.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/webview#2262]
https://katalyst01.cnx.org/contents/wpkg_88R@2.57:wGnkZ09p@4/Muscle-Tissue-and-Motion

![gluedtext](https://user-images.githubusercontent.com/47241114/59503392-8e9bd680-8ea0-11e9-969b-8c60936e8b72.jpeg)
Issue occurs in other locations too.

**Comment by brittweinstein** [comment]
assigning to @openstaxalina for prio

**Comment by openstaxalina** [comment]
This seems similar to https://github.com/openstax/webview/issues/2263; will park tomorrow.

**Comment by brittany-johnson** [comment]
<img width="898" alt="Screen Shot 2019-07-09 at 8 52 22 AM" src="https://user-images.githubusercontent.com/24909007/60893674-f5ee4180-a226-11e9-8faf-2ca35989fb78.png">

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/wpkg_88R@2.57:8x7YlLHu@4/Bone-Classification
tested on katalyst01
![Screenshot from 2019-07-16 16-06-23](https://user-images.githubusercontent.com/47241114/61301295-ec934500-a7e3-11e9-87de-c3f5f64f2b74.png)
