### ISSUE TITLE
Table top row bold lines.

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/webview#2263]
https://katalyst01.cnx.org/contents/wpkg_88R@2.57:kwbeYj9S@5/Bone-Structure

![bold](https://user-images.githubusercontent.com/47241114/59506379-4f718380-8ea8-11e9-9b4b-a2b594ef47f8.jpeg)

Table frame has to be smooth outside.

**Comment by brittweinstein** [comment]
assigning to @openstaxalina for prio

**Comment by openstaxalina** [comment]
It looks like `Bone Markings` is encoded as a table head, not a table title:
<img width="836" alt="Screen Shot 2019-06-16 at 3 54 26 PM" src="https://user-images.githubusercontent.com/7863733/59569444-16bfde80-904f-11e9-8dec-8e4ff0d77124.png">

Overall, the display of the table is clearer now, even if the table head is now within the table itself.  The textbook creator (note: this is a derived book) would be able to convert the table head into a title in the content if desired.  

I will park this with Hélène, BrittanyJ, Thomas, and Larissa, in case we want to make some kind of global styling exception for theads to move them outside the table.

**Comment by brittweinstein** [comment]
Decision: we will close b/c this is acceptable visually
