### ISSUE TITLE
What Would It Take to Support Italics in Module Titles?

### ISSUE THREAD

**Issue by openstaxalina** [openstax/webview#2265]
_The Florentine Codex_, the subject of [this module](https://content05.cnx.org/contents/CmIfJ6vh:JgybCbwI), should be italicized since we are referring to a book-like item.  However, CNX currently does not support italics in module titles. 

Would it be possible to support italics in module titles, as well as in the ToC?  What would this break?  Where/how would this need to be implemented?

**Comment by openstaxalina** [comment]
Need to apply the emphasis tags to some module title content to facilitate dev testing in a future sprint.

**Comment by openstaxalina** [comment]
Confirm that the markup is HTML markup - change some double braces to triple braces once you find the place in the template that renders that.  This would be a change in the webview repo. 

We would need a similar change in Tutor.  Need to also look at all the different spots where the titles display and confirm the italics show properly.  This is not a ton of work for dev, but more testing to make sure we found all the instances. 

Advice is to fix in CNX so that we get clean HTML and then see if further fixes are needed in Tutor.

**Comment by openstaxalina** [comment]
@oscryan, could you please create sample content with italics in the module titles on easyvm5.cnx.org and put the link here?  Please apply the template APUSH with recipe.

**Comment by oscryan** [comment]
https://easyvm5.cnx.org/contents/waJb6R7Y@2.1:VDwSTsFR@1/%E2%9C%92%EF%B8%8F-The-Florentine-Codex-c-1585

**Comment by brittweinstein** [comment]
We need to find where the title is rendered and ensure that the text does not escape. We will wait for easyvm5 to be cleaned up so we can test the content.

**Comment by openstaxalina** [comment]
@oscryan the link is leading to a 404.  Can you try publishing without the italics tags and see if it's still a 404?  Any troubleshooting would be welcome...we may need to publish a module title with italics on another server to see if this 404 issue is specific to easyvm5.

**Comment by openstaxalina** [comment]
Content troubleshooting steps from devs:

1) publish without italics tags, see if that works
2) publish again with italics tags, see if that works
3) if step 2 didn't work, try sub or sup tags or other markup that seems to work in page titles and see if **that** works

**Comment by oscryan** [comment]
https://easyvm5.cnx.org/contents/waJb6R7Y@2.1:VDwSTsFR@1/%E2%9C%92%EF%B8%8F-The-Florentine-Codex-c-1585

**Comment by oscryan** [comment]
https://easyvm5.cnx.org/content/col29682/latest/ the second module seems to work; html doesn't render in the editor, but webview notices it

**Comment by openstaxalina** [comment]
That is exciting!  Since we've had some weird behavior I want to document what I see:
![Screen Shot 2019-09-25 at 12 23 27 PM](https://user-images.githubusercontent.com/7863733/65624368-558afc00-df8f-11e9-85f9-82a6d194a972.png)

It appears that `<i>` works while `<emphasis effect="italics">` doesn't.  In both cases, the markup shows in Legacy (not desired, but doesn't matter because Legacy).  With `<emphasis effect="italics">`, nothing happens in CNX webview (see previous screenshot).  With `<i>`, the italics display in CNX webview (see previous screenshot).
![ItalicsMarkup](https://user-images.githubusercontent.com/7863733/65624564-c7fbdc00-df8f-11e9-9bc9-ecd6fd457ea4.png)

@oscryan could you test one more thing - could you test using `<i>` but having `c. 1585` in normal text?  I just want to make sure that we can have mixed (italics and non-italics) text in titles.  This will be important to inform WW's decisions.

If we decide that `<i>` works even with mixed (italics and non) titles, could you go ahead and change The Florentine Codex module on content05 and reimport to tutor-content to see if it works there, too?

**Comment by openstaxalina** [comment]
Side note that I am still getting 404s when pasting the URL to either of the above modules directly into my browser.  Probably need to check with devs about this.  Video here: https://drive.google.com/open?id=1gfY5Mzl5jDRZPoCuNHqmtA1RhV5MmkXP

**Comment by openstaxalina** [comment]
Another mystery is why the exact same markup yields italics on easyvm5 but not content05:
https://content05.cnx.org/contents/CmIfJ6vh@35.32:JgybCbwI@8/1-15-%E2%9C%92%EF%B8%8F-The-Florentine-Codex-c-1585

https://easyvm5.cnx.org/contents/waJb6R7Y@3.2:bChHirvQ@2/%E2%9C%92%EF%B8%8F-The-Florentine-Codex-c-1585

Park with devs tomorrow

**Comment by openstaxalina** [comment]
Results of team investigation:

The content on easyvm5 was NOT baked (we all confirmed this via Inspect).  The baking is stripping off the `<i> `tags.

Screenshot of unbaked content on easyvm5:
![Screen Shot 2019-09-26 at 11 13 18 AM](https://user-images.githubusercontent.com/7863733/65705830-ccd39500-e04e-11e9-9244-7566ad6d4f41.png)

Screenshot of baked content on content05:
![Screen Shot 2019-09-26 at 11 12 58 AM](https://user-images.githubusercontent.com/7863733/65705821-c7764a80-e04e-11e9-88bc-ec00f0c75ad7.png)

**Next steps:**
1) fix bug in cnx-recipes that is stripping any markup inside of a title (`sup` and `sub` will still be supported; if other page titles have markup this may not be supported)

_(Secret next steps: long live properly transformed cnxml)_

**Comment by openstaxalina** [comment]
Issue moved to [openstax/cnx-recipes #1429](https://github.com/openstax/cnx-recipes/issues/1429) via [**ZenHub**](https://www.zenhub.com/)
