### ISSUE TITLE
APUSH: Move Exercise Text onto the Line with Its Number

### ISSUE THREAD

**Issue by openstaxalina** [openstax/webview#2266]
@openstaxalina commented on [Fri Jun 28 2019](https://github.com/openstax/cnx-recipes/issues/1171)

# Scenario

The text of any exercise should be in line with its number, **not** on the line below.

For example, in [this module](https://staging.cnx.org/contents/KC8KeLYF@2.1:nx-LSZj6@5/1-1-%F0%9F%93%8E-Inquiry-Organizer)...
![APUSHExerciseTxtSameLine](https://user-images.githubusercontent.com/7863733/60372824-afe1e400-99c3-11e9-97b3-ff3c6ab963e6.png)

# Environment:

* **Medium**: [ ] REX [ ] PDF  [x] cnx.org  

# Test Plan 

# Acceptance Criteria
-Exercise text appears on the same line as the exercise number.

---

@tomjw64 commented on [Thu Jul 11 2019](https://github.com/openstax/cnx-recipes/issues/1171#issuecomment-510549456)

This is a styling issue, not a recipe issue. Reassigning to @brittany-johnson

**Comment by brittany-johnson** [comment]
![Screen Shot 2019-07-15 at 3 21 10 PM](https://user-images.githubusercontent.com/24909007/61246347-3b71a980-a714-11e9-9f29-c6188b287e9c.png)

**Comment by Stackblocks** [comment]
for review with staging APUSH collection from the initial comment.

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c067f165-37c2-4b6a-bc5b-6a3e3a420fb1)

**Comment by openstaxalina** [comment]
It looks like this was fixed!  What do you think, Alan?
Screenshot from: https://staging.cnx.org/contents/KC8KeLYF@2.1:dSSl_YvL@2/1-17-%E2%9C%92%EF%B8%8F-Watercolors-of-Algonquian-Peoples-in-North-Carolina-1585
![Screen Shot 2019-07-25 at 4.13.53 PM.png](https://images.zenhubusercontent.com/5b57372fb01a900cfd923015/4817c4e1-8f6d-4895-a7f3-27c24c78548f)

**Comment by Stackblocks** [comment]
@openstaxalina It looks like questions that are importing correctly (read: not `MISSING EXERCISE` display correctly, while the missing ones still line break.

Since `MISSING EXERCISE` is not the desired end state, does this meet our definition of done?

![image](https://user-images.githubusercontent.com/12678235/61909411-b0549880-aef7-11e9-91bb-d2350e428ec8.png)

**Comment by openstaxalina** [comment]
@Stackblocks good point. I think that the production teams or I can retest this on content05, where the exercises should import properly.  Then we could (hopefully) close this issue.  Would that plan work?

**Comment by openstaxalina** [comment]
Unfortunately it looks like assessments pulled in from Exercises still have the line break:
![Screen Shot 2019-08-01 at 1 47 05 PM](https://user-images.githubusercontent.com/7863733/62319125-eb5c4c00-b462-11e9-8534-ba8e32c3ee3e.png)

link: https://content05.cnx.org/contents/CmIfJ6vh@30.1:CtEXAR4u@12/1-3-%F0%9F%94%8E-Native-People

I am going to move this into o.o so we could take a look at this.  It may be a case of not having the proper test content on the proper servers.  I will note to park this on Monday. cc @Stackblocks @brittany-johnson

**Comment by Stackblocks** [comment]
Another point of interest there is that the Review Questions are behaving correctly, so it may be limited to Review Questions

**Comment by openstaxalina** [comment]
Review Questions and Test Prep for AP Courses are the only two exercise types in the title that pull in from Exercises - I think pulling in from Exercises seems to cause/be related to the display problem.

**Comment by openstaxalina** [comment]
Module with test content: https://staging.cnx.org/contents/KC8KeLYF:w01bi3xv

Need to determine what instance of Exercises easyvm5 points to.  

Might need a CM to encode 2-3 exercises with the relevant nicknames on THAT instance of Exercises.

**Comment by openstaxalina** [comment]
@dtwilliamson confirmed that easyvm5 is pointing to production exercises.

**Comment by openstaxalina** [comment]
not fixing now; webview is not the destination platform for APUSH.  The exercises are already displaying without the line break in Tutor.
