### ISSUE TITLE
Alignment is broken for stepwise lists in Chemistry

### ISSUE THREAD

**Issue by oscryan** [openstax/webview#2269]
https://cnx.org/contents/2bhe5sV_@5.10:N_6vCCqT@5/13-4-Equilibrium-Calculations

Webview:
<img width="335" alt="Screen Shot 2019-07-25 at 5 02 12 PM" src="https://user-images.githubusercontent.com/1895432/61911765-fd3b6d80-aefd-11e9-9792-c63a922329fc.png">

Rex test left, PDF right:
<img width="1214" alt="Screen Shot 2019-07-25 at 4 55 48 PM" src="https://user-images.githubusercontent.com/1895432/61911786-088e9900-aefe-11e9-8c5a-c36807d21e38.png">

**Comment by openstaxalina** [comment]
Issue moved to [openstax/unified #430](https://github.com/openstax/unified/issues/430) via [**ZenHub**](https://www.zenhub.com/)
