### ISSUE TITLE
Multiple Paragraphs Appearing as One

### ISSUE THREAD

**Issue by marcjeannott** [openstax/webview#2271]
In AP Biology Science Practice Challenge Questions, the last paragraph is actually suppose to be multiple paragraphs, yet appears as one on CNX. Below I've posted images of how it's marked up in the editor (with multiple paragraphs) ![2019-08-12_12-34-35.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/832a5b45-d5dc-400a-be07-50e49af43647)

How it looks on the PDF and Rex
![2019-08-12_12-35-23.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/1d792977-d971-4b9b-a251-4c98a6f94169)

How it looks on CNX. ( https://cnx.org/contents/bDIuMp-w@18.4:mQvIJaS1@18.4/Science-Practice-Challenge-Questions)
![2019-08-12_12-44-36.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/46ce9845-a226-49d3-bd5f-57b07ffe5c22)

**Comment by brittweinstein** [comment]
Decision: Will not fix as this is going to REX soon.
