### ISSUE TITLE
para tag not rendering in collated Homework in Introductory Statistics

### ISSUE THREAD

**Issue by oscryan** [openstax/webview#2273]
https://cnx.org/contents/MBiUQmmY@23.33:2uU19ocf@23.33/Homework

<img width="689" alt="Screen Shot 2019-09-09 at 9 21 08 AM" src="https://user-images.githubusercontent.com/1895432/64538943-30399500-d2e3-11e9-8610-27457f353a93.png">

the markup here is `<para id="eip-idp85002752">
Did the silver content of the coins change over the course of Manuel’s reign?
</para>
<para id="eip-idm32834512">
Here are the means and variances of each coinage. The data are unbalanced.
</para>`

**Comment by oscryan** [comment]
It is also not rendering in the collating Additional Problems section in University Physics:
https://cnx.org/contents/rydUIGBQ@12.20:HcDhqVVe@12.20/Additional-Problems
<img width="1404" alt="Screen Shot 2019-09-09 at 10 55 15 AM" src="https://user-images.githubusercontent.com/1895432/64547763-efe21300-d2f2-11e9-8a86-5c5ef8aeffd5.png">

`<para id="fs-id1172102122026">
Each of the following reactions is missing a single particle. Identify the missing particle for each reaction.
</para>
<para id="fs-id1172101730885">
<m:math>
<m:mtable>
<m:mtr>
<m:mtd columnalign="left">
<m:mtext>(a)</m:mtext>
<m:mspace width="0.2em"/>
<m:mtext>p</m:mtext>
<m:mo>+</m:mo>
<m:mover>
<m:mtext>p</m:mtext>
<m:mtext>−</m:mtext>
</m:mover>
<m:mo stretchy="false">→</m:mo>
<m:mtext>n</m:mtext>
<m:mo>+</m:mo>
<m:mo>?</m:mo>...`

**Comment by brittweinstein** [comment]
@lwtchu @openstaxalina what is the prio here?

**Comment by lwtchu** [comment]
<img width="582" alt="Screen Shot 2020-05-27 at 12 06 38 PM" src="https://user-images.githubusercontent.com/11299125/83050699-8a65bc00-a012-11ea-904a-b8a9dc2efc36.png">

fixed on rex. might've been a webview issue only.
