### ISSUE TITLE
WAITING TO TEST IN REX: Captions too lightly colored in Statistics

### ISSUE THREAD

**Issue by lwtchu** [openstax/webview#2276]
@marcjeannott commented on [Thu Sep 26 2019](https://github.com/openstax/cnx-recipes/issues/1422)

# What happened?
While testing Statistics I noticed the table captions are so light it's difficult to read. 

# Reproducibility Details
You can find this content on Table 1.8 -  https://content04.cnx.org/contents/8fd0axzV@4.1:km7EgaMp@2/1-2-Data-Sampling-and-Variation-in-Data-and-Sampling

# Environment:
Content04
- **Book(s)**: Stats
- **URL/Server**:  See above
- **Browser**: Chrome

# Screenshots
![2019-09-26_14-50-11.jpg](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/a0acfc13-9c32-4b8d-8020-4878ccb3bc46)

# Additional notes

**Comment by openstaxalina** [comment]
@lwtchu are you recommending content investigation on this or is this ready for dev work?

You had mentioned that there was a table caption somewhere else that **was** appearing properly; did you find the markup for that?

**Comment by lwtchu** [comment]
@openstaxalina Can confirm this is in the table caption and not a footer row.

I think I got confused with the other table titles.

The design should follow how figure caption and titles work. Should match base font color. Titles should be bold and captions are not.

**Comment by openstaxalina** [comment]
Most likely this will need to be fixed in REX once we can test content there.

Putting in the Icebox until we have statistics ready to migrate to production and put in a REX sandbox for testing.

**Comment by brittweinstein** [comment]
@lwtchu can we confirm that this is no longer an issue: https://openstax.org/books/introductory-statistics/pages/1-introduction

**Comment by lwtchu** [comment]
Fyi it's in hs stats not intro stats: https://openstax.org/books/statistics/pages/1-2-data-sampling-and-variation-in-data-and-sampling

<img width="878" alt="Screen Shot 2020-05-27 at 10 59 23 AM" src="https://user-images.githubusercontent.com/11299125/83043979-2d193d00-a009-11ea-8580-161405ae815c.png">
verified not an issue
