### ISSUE TITLE
APUSH: Multi-part assessments not numbered correctly in Reference View

### ISSUE THREAD

**Issue by openstaxalina** [openstax/webview#2278]
@mwest-WWprod commented on [Mon Sep 16 2019](https://github.com/openstax/tutor/issues/601)

GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/course/88

Multi-part assessments are assigned a single assessment number in the Student/Teacher Reference View. This will mismatch the Instructor Answer Guide ancillary in which each part is individually numbered. Each separate question under the stimuli (stimuli not shown here, see #602 ). Let us know if this is a markup issue and we will account for it.

For reference, see our manuscript (which our XML team uses to tag content)
![multi-part_assessments_APUSH MS](https://user-images.githubusercontent.com/19212926/64975251-86c34800-d87c-11e9-8cb8-4f138f4ea3d4.JPG)

Reference View Output
![multi-part_assessments_APUSH](https://user-images.githubusercontent.com/19212926/64975584-5def8280-d87d-11e9-9a50-d6ddbc6e4c67.png)

---

@carlycurran commented on [Tue Sep 17 2019](https://github.com/openstax/tutor/issues/601#issuecomment-532368125)

@mwest-WWprod 

This is definitely an issue in Tutor. For now, this is how Tutor works -- a multi-part question is counted as one question. For a few reasons, I am planning to do some work in Q4 to change this. If we have this ready in Jan, will that work for you?

cc @openstaxalina 

---

@mwest-WWprod commented on [Tue Sep 24 2019](https://github.com/openstax/tutor/issues/601#issuecomment-534653149)

@carlycurran Thanks for the context, we'll confer on this, we may need to find a short-term workaround for an upcoming pilot, I'll add this to our discussion items for our working session on 9/26.

**Comment by openstaxalina** [comment]
@brittany-johnson would you be able to take a look at this?  I'm wondering if it would make sense to do this while you're working on https://github.com/openstax/webview/issues/2274.

https://github.com/openstax/webview/issues/2274 is definitely still the bigger priority, though.

**Comment by openstaxalina** [comment]
(The gist is that we want the stimulus to NOT be numbered, and we want the questions under the stimulus to be numbered, like in the manuscript screenshot above.)

**Comment by openstaxalina** [comment]
Discussed in person with BrittanyJ - she is going to look at this as part of #2274, but this issue (2278) may slide to t.t.

**Comment by openstaxalina** [comment]
The exercises are pulled in by cnx-epub **after** baking occurs (numbers are assigned during baking).  So right now we don't seem to be able to target each question under the stimulus to assign a number.  

@brittany-johnson and @tomjw64 proposed an alphabetic schema for the questions: 1A, B, C for example:
![Screen Shot 2019-10-15 at 10 45 39 AM](https://user-images.githubusercontent.com/7863733/67118311-3c4e2780-f1aa-11e9-8ef7-0b8e48662068.png)

Feedback from BRI is that it is best to have some type of numerical distinction among the questions to minimize confusion and approximate what the student will experience on the AP Exam.  It is confusing to have 1A with answer choices a, b, c, d (even if one is uppercase and the others lowercase, this is still confusing).  

We should brainstorm possible other options:

- ideal is to have an unnumbered, or roman-numeral-numbered, **stimulus** with sub-questions 1, 2, 3 etc.  AP Practice Question numbers should continue throughout the module and then restart in a new module.

- less ideal is roman number numbering on the sub-questions: 1i, 1ii, 1iii, etc.

- we could set the numbers statically in the content but this would require suppressing them elsewhere in Tutor, so I would prefer to leave this option as a last resort.

**Comment by tomjw64** [comment]
An estimation for the options listed:

1/ideal - I don't think this is possible without a pipeline level change

2/less ideal - should be slightly less easy than the uppercase letters initially suggested, but still not difficult

3/last resort - I might resort to generated numbers with CSS before this, possibly. It's not very kosher in bakedpdf, but if we have to do it, we could

**Comment by openstaxalina** [comment]
Fourth "kind of hacky" option - add an attribute that says how many questions are in that exercise.  Then baking can adjust its numbering accordingly (i.e. allow space for 1-3, etc.).  However this is risky because we might decide to add or remove sub-questions.  Could be easy to get out of sync.  This would be another last resort option.

**Comment by openstaxalina** [comment]
Steps for the ideal fix:

1. move the injection out of cnx-epub and into the database triggers for baking (need to verify which repo has the code)

2. regression test any book that pulls in stuff from Exercises (AP Bio, I think HS Physics...any others?) OR make a recipe flag `if book = apush, then pull in the exercises earlier`. (We think the former is better for now - fix this for all books.) 

3. `cnx-recipes` change to implement the proper numbering

**Comment by karenc** [comment]
Hm... what I'm seeing is that the bakery CLI doesn't fetch exercises :neutral_face:  I added `<link class="os-embed" url="#ost/api/ex/k12phys-ch22-ex110"/>` to one of the module's `index.cnxml` and the html remains ` <a href="#ost/api/ex/k12phys-ch22-ex110" class="autogenerated-content"></a>` right till the end.

<summary>As for server side baking, exercises are fetched before the book is baked.
</summary>

<details>

This is the code that bakes a book:

https://github.com/openstax/cnx-publishing/blob/473fc9bfad495140e5f4a95436d54d5d6cee8291/cnxpublishing/subscribers.py#L167

```
    bake(binder, recipe_id, publisher, message, cursor=cursor)
```

https://github.com/openstax/cnx-publishing/blob/473fc9bfad495140e5f4a95436d54d5d6cee8291/cnxpublishing/bake.py#L73-L74

```
    includes = _formatter_callback_factory()
    binder = collate_models(binder, ruleset=recipe, includes=includes)
```

https://github.com/openstax/cnx-publishing/blob/473fc9bfad495140e5f4a95436d54d5d6cee8291/cnxpublishing/bake.py#L25-L55

```python
def _formatter_callback_factory():  # pragma: no cover
    """Returns a list of includes to be given to `cnxepub.collation.collate`.
    """
    includes = []
    exercise_url_template = '{baseUrl}/api/exercises?q={field}:"{{itemCode}}"'
    settings = get_current_registry().settings
    exercise_base_url = settings.get('embeddables.exercise.base_url', None)
    exercise_matches = [match.split(',', 1) for match in aslist(
        settings.get('embeddables.exercise.match', ''), flatten=False)]
    exercise_token = settings.get('embeddables.exercise.token', None)
    mathml_url = settings.get('mathmlcloud.url', None)
    memcache_servers = settings.get('memcache_servers')
    if memcache_servers:
        memcache_servers = memcache_servers.split()
    else:
        memcache_servers = None

    if exercise_base_url and exercise_matches:
        mc_client = None
        if memcache_servers:
            mc_client = memcache.Client(memcache_servers, debug=0)
        for (exercise_match, exercise_field) in exercise_matches:
            template = exercise_url_template.format(
                baseUrl=exercise_base_url, field=exercise_field)
            includes.append(exercise_callback_factory(exercise_match,
                                                      template,
                                                      mc_client,
                                                      exercise_token,
                                                      mathml_url))
    return includes
```

^ `includes` has the exercises stuff

https://github.com/openstax/cnx-epub/blob/master/cnxepub/collation.py#L54-L73

```python
def collate(binder, ruleset=None, includes=None):
    """Given a ``Binder`` as ``binder``, collate the content into a new set
    of models.
    Returns the collated binder.
    """
    html_formatter = SingleHTMLFormatter(binder, includes)
    raw_html = io.BytesIO(bytes(html_formatter))
    collated_html = io.BytesIO()

    if ruleset is None:
        # No ruleset found, so no cooking necessary.
        return binder

    easybake(ruleset, raw_html, collated_html)

    collated_html.seek(0)
    collated_binder = reconstitute(collated_html)

    return collated_binder
```

^ `includes` is passed in when the single raw html is generated

I tested this on content04 using `col10002`:

```python
#!/var/cnx/venvs/publishing/bin/python
         
import io
               
import psycopg2                           
from cnxarchive.scripts import export_epub
from cnxeasybake import Oven                      
from cnxepub.formatters import SingleHTMLFormatter                     
from cnxpublishing.bake import _get_recipe, _formatter_callback_factory
from cnxpublishing.subscribers import _get_recipe_ids
from lxml import etree              
from pyramid.paster import bootstrap

                          
collection_id = 'col10002'                    
env = bootstrap('/etc/cnx/publishing/app.ini')                
db_conn_str = env['registry'].settings['db-connection-string']
with psycopg2.connect(db_conn_str) as db_conn:
    with db_conn.cursor() as cursor:
        cursor.execute('''\     
            SELECT module_ident,                                 
                   ident_hash(uuid, major_version, minor_version)
            FROM latest_modules WHERE moduleid = %s''',
            (collection_id,))                       
        module_ident, ident_hash = cursor.fetchone()   
        print('module_ident: {} ident_hash: {}'.format(
            module_ident, ident_hash))
                                                         
        # from cnxpublishing.subscribers.baking_processor
        binder = export_epub.factory(ident_hash)          
        recipe_ids = _get_recipe_ids(module_ident, cursor)
                                      
        # from cnxpublishing.bake.bake             
        recipe = _get_recipe(recipe_ids[0], cursor)
        includes = _formatter_callback_factory()
                                
# from cnxepub.collation.collate                      
html_formatter = SingleHTMLFormatter(binder, includes)
raw_html = io.BytesIO(bytes(html_formatter))
with open('raw.xhtml', 'wb') as f:
    f.write(raw_html.read())
    raw_html.seek(0)                
print('raw html saved as raw.xhtml')
collated_html = io.BytesIO()
                                 
# from cnxepub.collation.easybake
html = etree.parse(raw_html)
oven = Oven(recipe)
oven.bake(html)
collated_html.write(etree.tostring(html))

collated_html.seek(0)
with open('collated.xhtml', 'wb') as f:
    f.write(collated_html.read())
print('collated / baked html saved as collated.xhtml')
```

And indeed, where the module `index.cnxml` has:

```xml
<problem id="fs-id1164354953958">                                                                 
<para id="fs-id1164354595396"><link class="os-embed" url="#ost/api/ex/k12phys-ch01-ex008"/></para>
</problem>
```

`raw.xhtml` has the exercise:

```xml
<div data-type="problem" id="auto_bce56955-d895-4ed6-a4ff-7a95ba6ff123_fs-id1164354953958">                         
<div>Which statement best compares and contrasts the aims and topics of natural philosophy had versus physics?</div>
            <ol data-number-style="lower-alpha">                                                 
                    <li>Natural philosophy included all aspects of nature including physics.</li>
                    <li>Natural philosophy included all aspects of nature excluding physics.</li>
                    <li>Natural philosophy and physics are different.</li>                 
                    <li>Natural philosophy and physics are essentially the same thing.</li>
            </ol>
</div>
```

And of course `collated.xhtml` also has the exercise:

```xml
<div data-type="problem" id="auto_bce56955-d895-4ed6-a4ff-7a95ba6ff123_fs-id1164354953958"><span class="os-title-label">Exercise </span><span class="os-number">1.6</span><div class="os-problem-container">
<div>Which statement best compares and contrasts the aims and topics of natural philosophy had versus physics?</div>
            <ol data-number-style="lower-alpha">
                    <li>Natural philosophy included all aspects of nature including physics.</li>
                    <li>Natural philosophy included all aspects of nature excluding physics.</li>
                    <li>Natural philosophy and physics are different.</li>
                    <li>Natural philosophy and physics are essentially the same thing.</li>
            </ol>
</div></div>
```

</details>

**Comment by openstaxalina** [comment]
We will need to make sure this is tested both locally (w/ CLI) and on the server.

**Comment by openstaxalina** [comment]
I think this is the issue CE Tech is working on: https://github.com/openstax/cnx/issues/747

And this webview issue is for @brittany-johnson once CE Tech is done.

More context: https://openstax.slack.com/archives/C0LA54Q5C/p1572278647384200

**Comment by omehes** [comment]
@openstaxalina That means I will be testing 747 only, not this issue (#2278), right?
@brittweinstein

**Comment by Stackblocks** [comment]
Yeah, i'll probably be the one testing this side since I did the testing for https://github.com/openstax/webview/issues/2274.

**Comment by openstaxalina** [comment]
@Stackblocks to paste a link to the content on easyvm5.

**Comment by Stackblocks** [comment]
Link to easyvm5.cnx.org dummy content: https://easyvm5.cnx.org/contents/I3AIQB35@12.1:iV27iQYm@2/1-6-Origins-of-the-Slave-Trade

**Comment by karenc** [comment]
@brittany-johnson exercise fetching is now working in nebuchadnezzar `v9.4.0`.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/cnx-recipes #1577](https://github.com/openstax/cnx-recipes/issues/1577) via [**ZenHub**](https://www.zenhub.com/)
