### ISSUE TITLE
hs physics: display of section exercises

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2287]
Number and content of exercises should display inline. 
Problem occurs for exercises inside modules: (e.g. https://katalyst01.cnx.org/contents/qRkBHZVu@4.2:T1clFaXi@3/14-1-Speed-of-Sound-Frequency-and-Wavelength)

![image](https://user-images.githubusercontent.com/40228854/72509179-4a622180-3847-11ea-8f23-a1d27322712f.png)

![image](https://user-images.githubusercontent.com/40228854/72509191-54842000-3847-11ea-9ae3-06341bc5fdf5.png)

NOTE: label **Exercise** will be removed by recipes https://github.com/openstax/cnx-recipes/issues/1758

**Comment by MartaSztuka** [comment]
https://katalyst01.cnx.org/contents/qRkBHZVu@4.2:_VnwQKLB@4/7-1-Kepler-s-Laws-of-Planetary-Motion
![Screenshot from 2020-01-23 11-57-34](https://user-images.githubusercontent.com/47241114/72978983-ac86cd80-3dd7-11ea-857b-cf696268fc06.png)

**Comment by MartaSztuka** [comment]
tested on https://katalyst01.cnx.org/contents/qRkBHZVu@7.29:T1clFaXi@4/14-1-Speed-of-Sound-Frequency-and-Wavelength
![Screenshot from 2020-02-17 13-42-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a962a517-d9cd-43ea-8d0a-923797b9aa17)
