### ISSUE TITLE
Double titles in composite chapters

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2289]
In composite chapters from EOC titles of composite pages appear twice (e.g. https://katalyst01.cnx.org/contents/CImQfPDv@8.46:92s-N-ry@8.46/Review-Exercises)

![image](https://user-images.githubusercontent.com/40228854/72518751-3f62bd80-3856-11ea-87e5-f622aa1b2860.png)

**Comment by MartaSztuka** [comment]
tested on https://katalyst01.cnx.org/contents/qRkBHZVu@4.2:lMaFCtXn@4.2/Short-Answer
![Screenshot from 2020-01-23 10-28-15](https://user-images.githubusercontent.com/47241114/72972748-4b0d3180-3dcc-11ea-8eb6-4ae2d23fd9c4.png)

**Comment by MartaSztuka** [comment]
tested on https://katalyst01.cnx.org/contents/qRkBHZVu@7.29:bX_wX-Pp@7.29/Short-Answer
![Screenshot from 2020-02-17 13-38-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c1bb8fe3-7053-4f5f-ad65-053ed22c1764)
