### ISSUE TITLE
Verify TOC link issues on cops (related to issue #768)

### ISSUE THREAD

**Issue by omehes** [openstax/webview#2291]
Creating this issue as per conversation with Thomas and Bey

Test TOC links and their page numbering in cops on prod as per info in
https://app.zenhub.com/workspaces/content-engineering-tech-team-5af1f4cc12da5e6d74331b60/issues/openstax/cnx/768

**Comment by omehes** [comment]
I checked this on cops.openstax.org and chapter numbering looks good now.
I leave it open for @openstaxalina to verify.

![chap_no.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/44b8bf69-19be-4d4f-a6d3-d6951f6a2653)

![chapt_no33.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/6d0791b4-4b8a-44d9-9c82-894c9b86d9c9)

**Comment by omehes** [comment]
@openstaxalina I saw completed hs-physics book on katalyst01. The pdf has links which still show incorrect numbering. Should the code be deployed to katalyst too?

![chap-no5.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/b57be01f-9d4d-4e6a-b199-eb4477c2f717)

**Comment by openstaxalina** [comment]
@omehes this may be because HS Physics doesn't have styles merged to master (I think).  I'll go ahead and close this issue since you verified with Chemistry (which does have styles merged to master).
