### ISSUE TITLE
WAITING: Exercises in new line in Polish U-Physics

### ISSUE THREAD

**Issue by brittweinstein** [openstax/webview#2294]
@wilkus27 commented on [Thu Dec 19 2019](https://github.com/openstax/cnx-recipes/issues/1711)

Some of the exercises display in-line with number, but part of them below: 

![image](https://user-images.githubusercontent.com/40228854/71187262-021f0600-227f-11ea-85cd-15bea47605ca.png)

All of them should display in-line (exception: if exercise start with list it should be below the number like in exercise 47). 

Link: https://cnx.org/contents/TqqPA4io@1.153:MYKxrnA7@1.153/Podsumowanie-rozdzia%C5%82u

---

@wilkus27 commented on [Thu Dec 19 2019](https://github.com/openstax/cnx-recipes/issues/1711#issuecomment-567548713)

After investigation we have found with Krzysztof that content of the exercises is just in the `<p>`. To display correctly it should be wrapped into the div with class `os-problem-container`.

This class should be added by recipes.

The conclusion is, that either book is not baked with new recipes or `recipe.css` is not removed from the book.

---

@brittweinstein commented on [Mon Mar 02 2020](https://github.com/openstax/cnx-recipes/issues/1711#issuecomment-593476250)

We need to ensure that this is still an issue - the Fizyka recipe should be enabled and published on production to verify this. 

---

@brittweinstein commented on [Mon Mar 02 2020](https://github.com/openstax/cnx-recipes/issues/1711#issuecomment-593476837)

This work will also need to be done on REX.

**Comment by openstaxalina** [comment]
Issue moved to [openstax/unified #895](https://github.com/openstax/unified/issues/895) via [**ZenHub**](https://www.zenhub.com/)
