### ISSUE TITLE
unwanted artifacts in neb get progress output (via distr pipeline)

### ISSUE THREAD

**Issue by omehes** [openstax/webview#2299]
When you run book baking and uploading via distribution pipeline, in fetch book phase the neb get progress output shows 

```
+ neb get -r -d col12087/raw staging.cnx.org col12087 1.10
25lGetting col12087/raw  [###############################################]  186/18625h
```
incorrect page numbers: 186/18625h 

Discussed with Ripal: 
This does not happen when using neb get directly.

Seems like the output there gets “sandwiched” between 25l and 25h. Whatever it is has been there since the very first build: https://concourse-dev0.openstax.org/teams/Dev/pipelines/ce-cops-staging-bakery/jobs/bakery/builds/1

**Comment by brittweinstein** [comment]
This is a known issue that we will not fix.
