### ISSUE TITLE
New footnotes tags

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2301]
After tags for footnotes were changed text of footnote displays right after footnote number:

(https://staging.cnx.org/contents/TqqPA4io@3.11:Zx_pvyiS@6/1-1-Zakres-stosowalno%C5%9Bci-praw-fizyki)
![image](https://user-images.githubusercontent.com/40228854/97159796-aadda200-177b-11eb-9008-e5aaedffd6d7.png)

It should be moved to the end of the page:

![image](https://user-images.githubusercontent.com/40228854/97001662-066c1d80-1539-11eb-9009-3ea4724d4dcd.png)

**Comment by openstaxalina** [comment]
I think that this would be fixed when books are moved into REX, but that will happen in Q1 2021 at the earliest (per Kim).

I am curious if it is _possible_ to fix this issue on CNX, without undoing some of the recent transform work. cc @brittany-johnson @lwtchu may want to discuss the plan for this with Katalyst.

**Comment by lwtchu** [comment]
We could potentially apply the webview fix that REX did to cnx-webview and focus testing only on these titles. But I'll also await @brittany-johnson's input in case it's not as easy as I might've made it seem like :joy:

**Comment by wilkus27** [comment]
@openstaxalina @lwtchu we discussed it on one of our weekly call. We will apply similar solution to one from REX. Everything will be tested on staging.cnx.org, because there is old content on katalyst01.

Link to solution from REX: https://github.com/openstax/rex-web/pull/557/files

Link to book on staging: https://staging.cnx.org/contents/TqqPA4io@3.11:Zx_pvyiS@6/1-1-Zakres-stosowalno%C5%9Bci-praw-fizyki

**Comment by MartaSztuka** [comment]
#### PASSED
Tested on https://staging.cnx.org/contents/TqqPA4io@3.11:Zx_pvyiS@6/1-1-Zakres-stosowalno%C5%9Bci-praw-fizyki#fs-idm248304896
![Screenshot from 2020-11-12 09-39-18](https://user-images.githubusercontent.com/47241114/98916084-02de0d80-24cb-11eb-826b-92a75bf93884.png)
